// Code generated by ent, DO NOT EDIT.

package carpoolvehicletype

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the carpoolvehicletype type in the database.
	Label = "carpool_vehicle_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProduct holds the string denoting the product field in the database.
	FieldProduct = "product"
	// FieldPlanTier holds the string denoting the plan_tier field in the database.
	FieldPlanTier = "plan_tier"
	// FieldMultiplier holds the string denoting the multiplier field in the database.
	FieldMultiplier = "multiplier"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSeatCount holds the string denoting the seat_count field in the database.
	FieldSeatCount = "seat_count"
	// FieldTotalPrice holds the string denoting the total_price field in the database.
	FieldTotalPrice = "total_price"
	// FieldUnitPrice holds the string denoting the unit_price field in the database.
	FieldUnitPrice = "unit_price"
	// FieldServiceDays holds the string denoting the service_days field in the database.
	FieldServiceDays = "service_days"
	// FieldRefundWaitHours holds the string denoting the refund_wait_hours field in the database.
	FieldRefundWaitHours = "refund_wait_hours"
	// FieldCompletedBaseCount holds the string denoting the completed_base_count field in the database.
	FieldCompletedBaseCount = "completed_base_count"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldSupportRevenuePool holds the string denoting the support_revenue_pool field in the database.
	FieldSupportRevenuePool = "support_revenue_pool"
	// FieldRequireStaticIP holds the string denoting the require_static_ip field in the database.
	FieldRequireStaticIP = "require_static_ip"
	// FieldWaitDurationOptions holds the string denoting the wait_duration_options field in the database.
	FieldWaitDurationOptions = "wait_duration_options"
	// FieldRefundMethods holds the string denoting the refund_methods field in the database.
	FieldRefundMethods = "refund_methods"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeSessions holds the string denoting the sessions edge name in mutations.
	EdgeSessions = "sessions"
	// EdgeParticipants holds the string denoting the participants edge name in mutations.
	EdgeParticipants = "participants"
	// Table holds the table name of the carpoolvehicletype in the database.
	Table = "carpool_vehicle_types"
	// SessionsTable is the table that holds the sessions relation/edge.
	SessionsTable = "carpool_sessions"
	// SessionsInverseTable is the table name for the CarpoolSession entity.
	// It exists in this package in order to avoid circular dependency with the "carpoolsession" package.
	SessionsInverseTable = "carpool_sessions"
	// SessionsColumn is the table column denoting the sessions relation/edge.
	SessionsColumn = "vehicle_type_id"
	// ParticipantsTable is the table that holds the participants relation/edge.
	ParticipantsTable = "carpool_participants"
	// ParticipantsInverseTable is the table name for the CarpoolParticipant entity.
	// It exists in this package in order to avoid circular dependency with the "carpoolparticipant" package.
	ParticipantsInverseTable = "carpool_participants"
	// ParticipantsColumn is the table column denoting the participants relation/edge.
	ParticipantsColumn = "vehicle_type_id"
)

// Columns holds all SQL columns for carpoolvehicletype fields.
var Columns = []string{
	FieldID,
	FieldProduct,
	FieldPlanTier,
	FieldMultiplier,
	FieldName,
	FieldSeatCount,
	FieldTotalPrice,
	FieldUnitPrice,
	FieldServiceDays,
	FieldRefundWaitHours,
	FieldCompletedBaseCount,
	FieldEnabled,
	FieldSupportRevenuePool,
	FieldRequireStaticIP,
	FieldWaitDurationOptions,
	FieldRefundMethods,
	FieldDescription,
	FieldSortOrder,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultProduct holds the default value on creation for the "product" field.
	DefaultProduct string
	// ProductValidator is a validator for the "product" field. It is called by the builders before save.
	ProductValidator func(string) error
	// DefaultPlanTier holds the default value on creation for the "plan_tier" field.
	DefaultPlanTier string
	// PlanTierValidator is a validator for the "plan_tier" field. It is called by the builders before save.
	PlanTierValidator func(string) error
	// DefaultMultiplier holds the default value on creation for the "multiplier" field.
	DefaultMultiplier string
	// MultiplierValidator is a validator for the "multiplier" field. It is called by the builders before save.
	MultiplierValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultSeatCount holds the default value on creation for the "seat_count" field.
	DefaultSeatCount int
	// DefaultTotalPrice holds the default value on creation for the "total_price" field.
	DefaultTotalPrice float64
	// DefaultUnitPrice holds the default value on creation for the "unit_price" field.
	DefaultUnitPrice float64
	// DefaultServiceDays holds the default value on creation for the "service_days" field.
	DefaultServiceDays int
	// DefaultRefundWaitHours holds the default value on creation for the "refund_wait_hours" field.
	DefaultRefundWaitHours int
	// DefaultCompletedBaseCount holds the default value on creation for the "completed_base_count" field.
	DefaultCompletedBaseCount int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultSupportRevenuePool holds the default value on creation for the "support_revenue_pool" field.
	DefaultSupportRevenuePool bool
	// DefaultRequireStaticIP holds the default value on creation for the "require_static_ip" field.
	DefaultRequireStaticIP bool
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CarpoolVehicleType queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProduct orders the results by the product field.
func ByProduct(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProduct, opts...).ToFunc()
}

// ByPlanTier orders the results by the plan_tier field.
func ByPlanTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanTier, opts...).ToFunc()
}

// ByMultiplier orders the results by the multiplier field.
func ByMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMultiplier, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySeatCount orders the results by the seat_count field.
func BySeatCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeatCount, opts...).ToFunc()
}

// ByTotalPrice orders the results by the total_price field.
func ByTotalPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalPrice, opts...).ToFunc()
}

// ByUnitPrice orders the results by the unit_price field.
func ByUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitPrice, opts...).ToFunc()
}

// ByServiceDays orders the results by the service_days field.
func ByServiceDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceDays, opts...).ToFunc()
}

// ByRefundWaitHours orders the results by the refund_wait_hours field.
func ByRefundWaitHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundWaitHours, opts...).ToFunc()
}

// ByCompletedBaseCount orders the results by the completed_base_count field.
func ByCompletedBaseCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedBaseCount, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// BySupportRevenuePool orders the results by the support_revenue_pool field.
func BySupportRevenuePool(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupportRevenuePool, opts...).ToFunc()
}

// ByRequireStaticIP orders the results by the require_static_ip field.
func ByRequireStaticIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequireStaticIP, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySessionsCount orders the results by sessions count.
func BySessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSessionsStep(), opts...)
	}
}

// BySessions orders the results by sessions terms.
func BySessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByParticipantsCount orders the results by participants count.
func ByParticipantsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newParticipantsStep(), opts...)
	}
}

// ByParticipants orders the results by participants terms.
func ByParticipants(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParticipantsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
	)
}
func newParticipantsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ParticipantsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ParticipantsTable, ParticipantsColumn),
	)
}
