// Code generated by ent, DO NOT EDIT.

package lotterychance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldUserID, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldSourceType, v))
}

// SourceKey applies equality check predicate on the "source_key" field. It's identical to SourceKeyEQ.
func SourceKey(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldSourceKey, v))
}

// TotalCount applies equality check predicate on the "total_count" field. It's identical to TotalCountEQ.
func TotalCount(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldTotalCount, v))
}

// UsedCount applies equality check predicate on the "used_count" field. It's identical to UsedCountEQ.
func UsedCount(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldUsedCount, v))
}

// SourceAmount applies equality check predicate on the "source_amount" field. It's identical to SourceAmountEQ.
func SourceAmount(v float64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldSourceAmount, v))
}

// GrantDate applies equality check predicate on the "grant_date" field. It's identical to GrantDateEQ.
func GrantDate(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldGrantDate, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldExpiresAt, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldUserID, vs...))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceKeyEQ applies the EQ predicate on the "source_key" field.
func SourceKeyEQ(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldSourceKey, v))
}

// SourceKeyNEQ applies the NEQ predicate on the "source_key" field.
func SourceKeyNEQ(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldSourceKey, v))
}

// SourceKeyIn applies the In predicate on the "source_key" field.
func SourceKeyIn(vs ...string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldSourceKey, vs...))
}

// SourceKeyNotIn applies the NotIn predicate on the "source_key" field.
func SourceKeyNotIn(vs ...string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldSourceKey, vs...))
}

// SourceKeyGT applies the GT predicate on the "source_key" field.
func SourceKeyGT(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldSourceKey, v))
}

// SourceKeyGTE applies the GTE predicate on the "source_key" field.
func SourceKeyGTE(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldSourceKey, v))
}

// SourceKeyLT applies the LT predicate on the "source_key" field.
func SourceKeyLT(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldSourceKey, v))
}

// SourceKeyLTE applies the LTE predicate on the "source_key" field.
func SourceKeyLTE(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldSourceKey, v))
}

// SourceKeyContains applies the Contains predicate on the "source_key" field.
func SourceKeyContains(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldContains(FieldSourceKey, v))
}

// SourceKeyHasPrefix applies the HasPrefix predicate on the "source_key" field.
func SourceKeyHasPrefix(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldHasPrefix(FieldSourceKey, v))
}

// SourceKeyHasSuffix applies the HasSuffix predicate on the "source_key" field.
func SourceKeyHasSuffix(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldHasSuffix(FieldSourceKey, v))
}

// SourceKeyEqualFold applies the EqualFold predicate on the "source_key" field.
func SourceKeyEqualFold(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEqualFold(FieldSourceKey, v))
}

// SourceKeyContainsFold applies the ContainsFold predicate on the "source_key" field.
func SourceKeyContainsFold(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldContainsFold(FieldSourceKey, v))
}

// TotalCountEQ applies the EQ predicate on the "total_count" field.
func TotalCountEQ(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldTotalCount, v))
}

// TotalCountNEQ applies the NEQ predicate on the "total_count" field.
func TotalCountNEQ(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldTotalCount, v))
}

// TotalCountIn applies the In predicate on the "total_count" field.
func TotalCountIn(vs ...int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldTotalCount, vs...))
}

// TotalCountNotIn applies the NotIn predicate on the "total_count" field.
func TotalCountNotIn(vs ...int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldTotalCount, vs...))
}

// TotalCountGT applies the GT predicate on the "total_count" field.
func TotalCountGT(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldTotalCount, v))
}

// TotalCountGTE applies the GTE predicate on the "total_count" field.
func TotalCountGTE(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldTotalCount, v))
}

// TotalCountLT applies the LT predicate on the "total_count" field.
func TotalCountLT(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldTotalCount, v))
}

// TotalCountLTE applies the LTE predicate on the "total_count" field.
func TotalCountLTE(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldTotalCount, v))
}

// UsedCountEQ applies the EQ predicate on the "used_count" field.
func UsedCountEQ(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldUsedCount, v))
}

// UsedCountNEQ applies the NEQ predicate on the "used_count" field.
func UsedCountNEQ(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldUsedCount, v))
}

// UsedCountIn applies the In predicate on the "used_count" field.
func UsedCountIn(vs ...int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldUsedCount, vs...))
}

// UsedCountNotIn applies the NotIn predicate on the "used_count" field.
func UsedCountNotIn(vs ...int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldUsedCount, vs...))
}

// UsedCountGT applies the GT predicate on the "used_count" field.
func UsedCountGT(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldUsedCount, v))
}

// UsedCountGTE applies the GTE predicate on the "used_count" field.
func UsedCountGTE(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldUsedCount, v))
}

// UsedCountLT applies the LT predicate on the "used_count" field.
func UsedCountLT(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldUsedCount, v))
}

// UsedCountLTE applies the LTE predicate on the "used_count" field.
func UsedCountLTE(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldUsedCount, v))
}

// SourceAmountEQ applies the EQ predicate on the "source_amount" field.
func SourceAmountEQ(v float64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldSourceAmount, v))
}

// SourceAmountNEQ applies the NEQ predicate on the "source_amount" field.
func SourceAmountNEQ(v float64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldSourceAmount, v))
}

// SourceAmountIn applies the In predicate on the "source_amount" field.
func SourceAmountIn(vs ...float64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldSourceAmount, vs...))
}

// SourceAmountNotIn applies the NotIn predicate on the "source_amount" field.
func SourceAmountNotIn(vs ...float64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldSourceAmount, vs...))
}

// SourceAmountGT applies the GT predicate on the "source_amount" field.
func SourceAmountGT(v float64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldSourceAmount, v))
}

// SourceAmountGTE applies the GTE predicate on the "source_amount" field.
func SourceAmountGTE(v float64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldSourceAmount, v))
}

// SourceAmountLT applies the LT predicate on the "source_amount" field.
func SourceAmountLT(v float64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldSourceAmount, v))
}

// SourceAmountLTE applies the LTE predicate on the "source_amount" field.
func SourceAmountLTE(v float64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldSourceAmount, v))
}

// GrantDateEQ applies the EQ predicate on the "grant_date" field.
func GrantDateEQ(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldGrantDate, v))
}

// GrantDateNEQ applies the NEQ predicate on the "grant_date" field.
func GrantDateNEQ(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldGrantDate, v))
}

// GrantDateIn applies the In predicate on the "grant_date" field.
func GrantDateIn(vs ...time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldGrantDate, vs...))
}

// GrantDateNotIn applies the NotIn predicate on the "grant_date" field.
func GrantDateNotIn(vs ...time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldGrantDate, vs...))
}

// GrantDateGT applies the GT predicate on the "grant_date" field.
func GrantDateGT(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldGrantDate, v))
}

// GrantDateGTE applies the GTE predicate on the "grant_date" field.
func GrantDateGTE(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldGrantDate, v))
}

// GrantDateLT applies the LT predicate on the "grant_date" field.
func GrantDateLT(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldGrantDate, v))
}

// GrantDateLTE applies the LTE predicate on the "grant_date" field.
func GrantDateLTE(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldGrantDate, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldExpiresAt, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.LotteryChance {
	return predicate.LotteryChance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.LotteryChance {
	return predicate.LotteryChance(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDrawRecords applies the HasEdge predicate on the "draw_records" edge.
func HasDrawRecords() predicate.LotteryChance {
	return predicate.LotteryChance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DrawRecordsTable, DrawRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDrawRecordsWith applies the HasEdge predicate on the "draw_records" edge with a given conditions (other predicates).
func HasDrawRecordsWith(preds ...predicate.LotteryDrawRecord) predicate.LotteryChance {
	return predicate.LotteryChance(func(s *sql.Selector) {
		step := newDrawRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LotteryChance) predicate.LotteryChance {
	return predicate.LotteryChance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LotteryChance) predicate.LotteryChance {
	return predicate.LotteryChance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LotteryChance) predicate.LotteryChance {
	return predicate.LotteryChance(sql.NotPredicates(p))
}
