// Code generated by ent, DO NOT EDIT.

package lotterydrawrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the lotterydrawrecord type in the database.
	Label = "lottery_draw_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldChanceID holds the string denoting the chance_id field in the database.
	FieldChanceID = "chance_id"
	// FieldPrizeID holds the string denoting the prize_id field in the database.
	FieldPrizeID = "prize_id"
	// FieldPrizeName holds the string denoting the prize_name field in the database.
	FieldPrizeName = "prize_name"
	// FieldPrizeDescription holds the string denoting the prize_description field in the database.
	FieldPrizeDescription = "prize_description"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldBalanceBefore holds the string denoting the balance_before field in the database.
	FieldBalanceBefore = "balance_before"
	// FieldBalanceAfter holds the string denoting the balance_after field in the database.
	FieldBalanceAfter = "balance_after"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldConfigSnapshot holds the string denoting the config_snapshot field in the database.
	FieldConfigSnapshot = "config_snapshot"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeChance holds the string denoting the chance edge name in mutations.
	EdgeChance = "chance"
	// EdgePrize holds the string denoting the prize edge name in mutations.
	EdgePrize = "prize"
	// Table holds the table name of the lotterydrawrecord in the database.
	Table = "lottery_draw_records"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "lottery_draw_records"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// ChanceTable is the table that holds the chance relation/edge.
	ChanceTable = "lottery_draw_records"
	// ChanceInverseTable is the table name for the LotteryChance entity.
	// It exists in this package in order to avoid circular dependency with the "lotterychance" package.
	ChanceInverseTable = "lottery_chances"
	// ChanceColumn is the table column denoting the chance relation/edge.
	ChanceColumn = "chance_id"
	// PrizeTable is the table that holds the prize relation/edge.
	PrizeTable = "lottery_draw_records"
	// PrizeInverseTable is the table name for the LotteryPrize entity.
	// It exists in this package in order to avoid circular dependency with the "lotteryprize" package.
	PrizeInverseTable = "lottery_prizes"
	// PrizeColumn is the table column denoting the prize relation/edge.
	PrizeColumn = "prize_id"
)

// Columns holds all SQL columns for lotterydrawrecord fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldChanceID,
	FieldPrizeID,
	FieldPrizeName,
	FieldPrizeDescription,
	FieldAmount,
	FieldBalanceBefore,
	FieldBalanceAfter,
	FieldSourceType,
	FieldConfigSnapshot,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PrizeNameValidator is a validator for the "prize_name" field. It is called by the builders before save.
	PrizeNameValidator func(string) error
	// DefaultPrizeDescription holds the default value on creation for the "prize_description" field.
	DefaultPrizeDescription string
	// PrizeDescriptionValidator is a validator for the "prize_description" field. It is called by the builders before save.
	PrizeDescriptionValidator func(string) error
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultBalanceBefore holds the default value on creation for the "balance_before" field.
	DefaultBalanceBefore float64
	// DefaultBalanceAfter holds the default value on creation for the "balance_after" field.
	DefaultBalanceAfter float64
	// SourceTypeValidator is a validator for the "source_type" field. It is called by the builders before save.
	SourceTypeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the LotteryDrawRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByChanceID orders the results by the chance_id field.
func ByChanceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChanceID, opts...).ToFunc()
}

// ByPrizeID orders the results by the prize_id field.
func ByPrizeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeID, opts...).ToFunc()
}

// ByPrizeName orders the results by the prize_name field.
func ByPrizeName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeName, opts...).ToFunc()
}

// ByPrizeDescription orders the results by the prize_description field.
func ByPrizeDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeDescription, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByBalanceBefore orders the results by the balance_before field.
func ByBalanceBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceBefore, opts...).ToFunc()
}

// ByBalanceAfter orders the results by the balance_after field.
func ByBalanceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAfter, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByChanceField orders the results by chance field.
func ByChanceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChanceStep(), sql.OrderByField(field, opts...))
	}
}

// ByPrizeField orders the results by prize field.
func ByPrizeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrizeStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newChanceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChanceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChanceTable, ChanceColumn),
	)
}
func newPrizeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrizeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PrizeTable, PrizeColumn),
	)
}
