// Code generated by ent, DO NOT EDIT.

package carpoolsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the carpoolsession type in the database.
	Label = "carpool_session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVehicleTypeID holds the string denoting the vehicle_type_id field in the database.
	FieldVehicleTypeID = "vehicle_type_id"
	// FieldSessionNo holds the string denoting the session_no field in the database.
	FieldSessionNo = "session_no"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSeatCount holds the string denoting the seat_count field in the database.
	FieldSeatCount = "seat_count"
	// FieldPaidCount holds the string denoting the paid_count field in the database.
	FieldPaidCount = "paid_count"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFilledAt holds the string denoting the filled_at field in the database.
	FieldFilledAt = "filled_at"
	// FieldProvisionedAt holds the string denoting the provisioned_at field in the database.
	FieldProvisionedAt = "provisioned_at"
	// FieldServiceStartedAt holds the string denoting the service_started_at field in the database.
	FieldServiceStartedAt = "service_started_at"
	// FieldServiceEndedAt holds the string denoting the service_ended_at field in the database.
	FieldServiceEndedAt = "service_ended_at"
	// FieldAccountInfo holds the string denoting the account_info field in the database.
	FieldAccountInfo = "account_info"
	// FieldProxyInfo holds the string denoting the proxy_info field in the database.
	FieldProxyInfo = "proxy_info"
	// FieldCommunication holds the string denoting the communication field in the database.
	FieldCommunication = "communication"
	// FieldAdminNotes holds the string denoting the admin_notes field in the database.
	FieldAdminNotes = "admin_notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeVehicleType holds the string denoting the vehicle_type edge name in mutations.
	EdgeVehicleType = "vehicle_type"
	// EdgeParticipants holds the string denoting the participants edge name in mutations.
	EdgeParticipants = "participants"
	// EdgeVouchers holds the string denoting the vouchers edge name in mutations.
	EdgeVouchers = "vouchers"
	// Table holds the table name of the carpoolsession in the database.
	Table = "carpool_sessions"
	// VehicleTypeTable is the table that holds the vehicle_type relation/edge.
	VehicleTypeTable = "carpool_sessions"
	// VehicleTypeInverseTable is the table name for the CarpoolVehicleType entity.
	// It exists in this package in order to avoid circular dependency with the "carpoolvehicletype" package.
	VehicleTypeInverseTable = "carpool_vehicle_types"
	// VehicleTypeColumn is the table column denoting the vehicle_type relation/edge.
	VehicleTypeColumn = "vehicle_type_id"
	// ParticipantsTable is the table that holds the participants relation/edge.
	ParticipantsTable = "carpool_participants"
	// ParticipantsInverseTable is the table name for the CarpoolParticipant entity.
	// It exists in this package in order to avoid circular dependency with the "carpoolparticipant" package.
	ParticipantsInverseTable = "carpool_participants"
	// ParticipantsColumn is the table column denoting the participants relation/edge.
	ParticipantsColumn = "session_id"
	// VouchersTable is the table that holds the vouchers relation/edge.
	VouchersTable = "carpool_vouchers"
	// VouchersInverseTable is the table name for the CarpoolVoucher entity.
	// It exists in this package in order to avoid circular dependency with the "carpoolvoucher" package.
	VouchersInverseTable = "carpool_vouchers"
	// VouchersColumn is the table column denoting the vouchers relation/edge.
	VouchersColumn = "session_id"
)

// Columns holds all SQL columns for carpoolsession fields.
var Columns = []string{
	FieldID,
	FieldVehicleTypeID,
	FieldSessionNo,
	FieldStatus,
	FieldSeatCount,
	FieldPaidCount,
	FieldStartedAt,
	FieldFilledAt,
	FieldProvisionedAt,
	FieldServiceStartedAt,
	FieldServiceEndedAt,
	FieldAccountInfo,
	FieldProxyInfo,
	FieldCommunication,
	FieldAdminNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSessionNo holds the default value on creation for the "session_no" field.
	DefaultSessionNo string
	// SessionNoValidator is a validator for the "session_no" field. It is called by the builders before save.
	SessionNoValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultSeatCount holds the default value on creation for the "seat_count" field.
	DefaultSeatCount int
	// DefaultPaidCount holds the default value on creation for the "paid_count" field.
	DefaultPaidCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CarpoolSession queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByVehicleTypeID orders the results by the vehicle_type_id field.
func ByVehicleTypeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVehicleTypeID, opts...).ToFunc()
}

// BySessionNo orders the results by the session_no field.
func BySessionNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionNo, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySeatCount orders the results by the seat_count field.
func BySeatCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeatCount, opts...).ToFunc()
}

// ByPaidCount orders the results by the paid_count field.
func ByPaidCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidCount, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFilledAt orders the results by the filled_at field.
func ByFilledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilledAt, opts...).ToFunc()
}

// ByProvisionedAt orders the results by the provisioned_at field.
func ByProvisionedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvisionedAt, opts...).ToFunc()
}

// ByServiceStartedAt orders the results by the service_started_at field.
func ByServiceStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceStartedAt, opts...).ToFunc()
}

// ByServiceEndedAt orders the results by the service_ended_at field.
func ByServiceEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceEndedAt, opts...).ToFunc()
}

// ByAdminNotes orders the results by the admin_notes field.
func ByAdminNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByVehicleTypeField orders the results by vehicle_type field.
func ByVehicleTypeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVehicleTypeStep(), sql.OrderByField(field, opts...))
	}
}

// ByParticipantsCount orders the results by participants count.
func ByParticipantsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newParticipantsStep(), opts...)
	}
}

// ByParticipants orders the results by participants terms.
func ByParticipants(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParticipantsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByVouchersCount orders the results by vouchers count.
func ByVouchersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVouchersStep(), opts...)
	}
}

// ByVouchers orders the results by vouchers terms.
func ByVouchers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVouchersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newVehicleTypeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VehicleTypeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, VehicleTypeTable, VehicleTypeColumn),
	)
}
func newParticipantsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ParticipantsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ParticipantsTable, ParticipantsColumn),
	)
}
func newVouchersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VouchersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VouchersTable, VouchersColumn),
	)
}
