// Code generated by ent, DO NOT EDIT.

package carpoolsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLTE(FieldID, id))
}

// VehicleTypeID applies equality check predicate on the "vehicle_type_id" field. It's identical to VehicleTypeIDEQ.
func VehicleTypeID(v int64) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldVehicleTypeID, v))
}

// SessionNo applies equality check predicate on the "session_no" field. It's identical to SessionNoEQ.
func SessionNo(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldSessionNo, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldStatus, v))
}

// SeatCount applies equality check predicate on the "seat_count" field. It's identical to SeatCountEQ.
func SeatCount(v int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldSeatCount, v))
}

// PaidCount applies equality check predicate on the "paid_count" field. It's identical to PaidCountEQ.
func PaidCount(v int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldPaidCount, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldStartedAt, v))
}

// FilledAt applies equality check predicate on the "filled_at" field. It's identical to FilledAtEQ.
func FilledAt(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldFilledAt, v))
}

// ProvisionedAt applies equality check predicate on the "provisioned_at" field. It's identical to ProvisionedAtEQ.
func ProvisionedAt(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldProvisionedAt, v))
}

// ServiceStartedAt applies equality check predicate on the "service_started_at" field. It's identical to ServiceStartedAtEQ.
func ServiceStartedAt(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldServiceStartedAt, v))
}

// ServiceEndedAt applies equality check predicate on the "service_ended_at" field. It's identical to ServiceEndedAtEQ.
func ServiceEndedAt(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldServiceEndedAt, v))
}

// AdminNotes applies equality check predicate on the "admin_notes" field. It's identical to AdminNotesEQ.
func AdminNotes(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldAdminNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// VehicleTypeIDEQ applies the EQ predicate on the "vehicle_type_id" field.
func VehicleTypeIDEQ(v int64) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldVehicleTypeID, v))
}

// VehicleTypeIDNEQ applies the NEQ predicate on the "vehicle_type_id" field.
func VehicleTypeIDNEQ(v int64) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNEQ(FieldVehicleTypeID, v))
}

// VehicleTypeIDIn applies the In predicate on the "vehicle_type_id" field.
func VehicleTypeIDIn(vs ...int64) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIn(FieldVehicleTypeID, vs...))
}

// VehicleTypeIDNotIn applies the NotIn predicate on the "vehicle_type_id" field.
func VehicleTypeIDNotIn(vs ...int64) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotIn(FieldVehicleTypeID, vs...))
}

// SessionNoEQ applies the EQ predicate on the "session_no" field.
func SessionNoEQ(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldSessionNo, v))
}

// SessionNoNEQ applies the NEQ predicate on the "session_no" field.
func SessionNoNEQ(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNEQ(FieldSessionNo, v))
}

// SessionNoIn applies the In predicate on the "session_no" field.
func SessionNoIn(vs ...string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIn(FieldSessionNo, vs...))
}

// SessionNoNotIn applies the NotIn predicate on the "session_no" field.
func SessionNoNotIn(vs ...string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotIn(FieldSessionNo, vs...))
}

// SessionNoGT applies the GT predicate on the "session_no" field.
func SessionNoGT(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGT(FieldSessionNo, v))
}

// SessionNoGTE applies the GTE predicate on the "session_no" field.
func SessionNoGTE(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGTE(FieldSessionNo, v))
}

// SessionNoLT applies the LT predicate on the "session_no" field.
func SessionNoLT(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLT(FieldSessionNo, v))
}

// SessionNoLTE applies the LTE predicate on the "session_no" field.
func SessionNoLTE(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLTE(FieldSessionNo, v))
}

// SessionNoContains applies the Contains predicate on the "session_no" field.
func SessionNoContains(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldContains(FieldSessionNo, v))
}

// SessionNoHasPrefix applies the HasPrefix predicate on the "session_no" field.
func SessionNoHasPrefix(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldHasPrefix(FieldSessionNo, v))
}

// SessionNoHasSuffix applies the HasSuffix predicate on the "session_no" field.
func SessionNoHasSuffix(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldHasSuffix(FieldSessionNo, v))
}

// SessionNoEqualFold applies the EqualFold predicate on the "session_no" field.
func SessionNoEqualFold(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEqualFold(FieldSessionNo, v))
}

// SessionNoContainsFold applies the ContainsFold predicate on the "session_no" field.
func SessionNoContainsFold(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldContainsFold(FieldSessionNo, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldContainsFold(FieldStatus, v))
}

// SeatCountEQ applies the EQ predicate on the "seat_count" field.
func SeatCountEQ(v int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldSeatCount, v))
}

// SeatCountNEQ applies the NEQ predicate on the "seat_count" field.
func SeatCountNEQ(v int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNEQ(FieldSeatCount, v))
}

// SeatCountIn applies the In predicate on the "seat_count" field.
func SeatCountIn(vs ...int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIn(FieldSeatCount, vs...))
}

// SeatCountNotIn applies the NotIn predicate on the "seat_count" field.
func SeatCountNotIn(vs ...int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotIn(FieldSeatCount, vs...))
}

// SeatCountGT applies the GT predicate on the "seat_count" field.
func SeatCountGT(v int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGT(FieldSeatCount, v))
}

// SeatCountGTE applies the GTE predicate on the "seat_count" field.
func SeatCountGTE(v int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGTE(FieldSeatCount, v))
}

// SeatCountLT applies the LT predicate on the "seat_count" field.
func SeatCountLT(v int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLT(FieldSeatCount, v))
}

// SeatCountLTE applies the LTE predicate on the "seat_count" field.
func SeatCountLTE(v int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLTE(FieldSeatCount, v))
}

// PaidCountEQ applies the EQ predicate on the "paid_count" field.
func PaidCountEQ(v int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldPaidCount, v))
}

// PaidCountNEQ applies the NEQ predicate on the "paid_count" field.
func PaidCountNEQ(v int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNEQ(FieldPaidCount, v))
}

// PaidCountIn applies the In predicate on the "paid_count" field.
func PaidCountIn(vs ...int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIn(FieldPaidCount, vs...))
}

// PaidCountNotIn applies the NotIn predicate on the "paid_count" field.
func PaidCountNotIn(vs ...int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotIn(FieldPaidCount, vs...))
}

// PaidCountGT applies the GT predicate on the "paid_count" field.
func PaidCountGT(v int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGT(FieldPaidCount, v))
}

// PaidCountGTE applies the GTE predicate on the "paid_count" field.
func PaidCountGTE(v int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGTE(FieldPaidCount, v))
}

// PaidCountLT applies the LT predicate on the "paid_count" field.
func PaidCountLT(v int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLT(FieldPaidCount, v))
}

// PaidCountLTE applies the LTE predicate on the "paid_count" field.
func PaidCountLTE(v int) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLTE(FieldPaidCount, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotNull(FieldStartedAt))
}

// FilledAtEQ applies the EQ predicate on the "filled_at" field.
func FilledAtEQ(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldFilledAt, v))
}

// FilledAtNEQ applies the NEQ predicate on the "filled_at" field.
func FilledAtNEQ(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNEQ(FieldFilledAt, v))
}

// FilledAtIn applies the In predicate on the "filled_at" field.
func FilledAtIn(vs ...time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIn(FieldFilledAt, vs...))
}

// FilledAtNotIn applies the NotIn predicate on the "filled_at" field.
func FilledAtNotIn(vs ...time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotIn(FieldFilledAt, vs...))
}

// FilledAtGT applies the GT predicate on the "filled_at" field.
func FilledAtGT(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGT(FieldFilledAt, v))
}

// FilledAtGTE applies the GTE predicate on the "filled_at" field.
func FilledAtGTE(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGTE(FieldFilledAt, v))
}

// FilledAtLT applies the LT predicate on the "filled_at" field.
func FilledAtLT(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLT(FieldFilledAt, v))
}

// FilledAtLTE applies the LTE predicate on the "filled_at" field.
func FilledAtLTE(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLTE(FieldFilledAt, v))
}

// FilledAtIsNil applies the IsNil predicate on the "filled_at" field.
func FilledAtIsNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIsNull(FieldFilledAt))
}

// FilledAtNotNil applies the NotNil predicate on the "filled_at" field.
func FilledAtNotNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotNull(FieldFilledAt))
}

// ProvisionedAtEQ applies the EQ predicate on the "provisioned_at" field.
func ProvisionedAtEQ(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldProvisionedAt, v))
}

// ProvisionedAtNEQ applies the NEQ predicate on the "provisioned_at" field.
func ProvisionedAtNEQ(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNEQ(FieldProvisionedAt, v))
}

// ProvisionedAtIn applies the In predicate on the "provisioned_at" field.
func ProvisionedAtIn(vs ...time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIn(FieldProvisionedAt, vs...))
}

// ProvisionedAtNotIn applies the NotIn predicate on the "provisioned_at" field.
func ProvisionedAtNotIn(vs ...time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotIn(FieldProvisionedAt, vs...))
}

// ProvisionedAtGT applies the GT predicate on the "provisioned_at" field.
func ProvisionedAtGT(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGT(FieldProvisionedAt, v))
}

// ProvisionedAtGTE applies the GTE predicate on the "provisioned_at" field.
func ProvisionedAtGTE(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGTE(FieldProvisionedAt, v))
}

// ProvisionedAtLT applies the LT predicate on the "provisioned_at" field.
func ProvisionedAtLT(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLT(FieldProvisionedAt, v))
}

// ProvisionedAtLTE applies the LTE predicate on the "provisioned_at" field.
func ProvisionedAtLTE(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLTE(FieldProvisionedAt, v))
}

// ProvisionedAtIsNil applies the IsNil predicate on the "provisioned_at" field.
func ProvisionedAtIsNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIsNull(FieldProvisionedAt))
}

// ProvisionedAtNotNil applies the NotNil predicate on the "provisioned_at" field.
func ProvisionedAtNotNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotNull(FieldProvisionedAt))
}

// ServiceStartedAtEQ applies the EQ predicate on the "service_started_at" field.
func ServiceStartedAtEQ(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldServiceStartedAt, v))
}

// ServiceStartedAtNEQ applies the NEQ predicate on the "service_started_at" field.
func ServiceStartedAtNEQ(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNEQ(FieldServiceStartedAt, v))
}

// ServiceStartedAtIn applies the In predicate on the "service_started_at" field.
func ServiceStartedAtIn(vs ...time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIn(FieldServiceStartedAt, vs...))
}

// ServiceStartedAtNotIn applies the NotIn predicate on the "service_started_at" field.
func ServiceStartedAtNotIn(vs ...time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotIn(FieldServiceStartedAt, vs...))
}

// ServiceStartedAtGT applies the GT predicate on the "service_started_at" field.
func ServiceStartedAtGT(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGT(FieldServiceStartedAt, v))
}

// ServiceStartedAtGTE applies the GTE predicate on the "service_started_at" field.
func ServiceStartedAtGTE(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGTE(FieldServiceStartedAt, v))
}

// ServiceStartedAtLT applies the LT predicate on the "service_started_at" field.
func ServiceStartedAtLT(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLT(FieldServiceStartedAt, v))
}

// ServiceStartedAtLTE applies the LTE predicate on the "service_started_at" field.
func ServiceStartedAtLTE(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLTE(FieldServiceStartedAt, v))
}

// ServiceStartedAtIsNil applies the IsNil predicate on the "service_started_at" field.
func ServiceStartedAtIsNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIsNull(FieldServiceStartedAt))
}

// ServiceStartedAtNotNil applies the NotNil predicate on the "service_started_at" field.
func ServiceStartedAtNotNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotNull(FieldServiceStartedAt))
}

// ServiceEndedAtEQ applies the EQ predicate on the "service_ended_at" field.
func ServiceEndedAtEQ(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldServiceEndedAt, v))
}

// ServiceEndedAtNEQ applies the NEQ predicate on the "service_ended_at" field.
func ServiceEndedAtNEQ(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNEQ(FieldServiceEndedAt, v))
}

// ServiceEndedAtIn applies the In predicate on the "service_ended_at" field.
func ServiceEndedAtIn(vs ...time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIn(FieldServiceEndedAt, vs...))
}

// ServiceEndedAtNotIn applies the NotIn predicate on the "service_ended_at" field.
func ServiceEndedAtNotIn(vs ...time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotIn(FieldServiceEndedAt, vs...))
}

// ServiceEndedAtGT applies the GT predicate on the "service_ended_at" field.
func ServiceEndedAtGT(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGT(FieldServiceEndedAt, v))
}

// ServiceEndedAtGTE applies the GTE predicate on the "service_ended_at" field.
func ServiceEndedAtGTE(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGTE(FieldServiceEndedAt, v))
}

// ServiceEndedAtLT applies the LT predicate on the "service_ended_at" field.
func ServiceEndedAtLT(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLT(FieldServiceEndedAt, v))
}

// ServiceEndedAtLTE applies the LTE predicate on the "service_ended_at" field.
func ServiceEndedAtLTE(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLTE(FieldServiceEndedAt, v))
}

// ServiceEndedAtIsNil applies the IsNil predicate on the "service_ended_at" field.
func ServiceEndedAtIsNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIsNull(FieldServiceEndedAt))
}

// ServiceEndedAtNotNil applies the NotNil predicate on the "service_ended_at" field.
func ServiceEndedAtNotNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotNull(FieldServiceEndedAt))
}

// AccountInfoIsNil applies the IsNil predicate on the "account_info" field.
func AccountInfoIsNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIsNull(FieldAccountInfo))
}

// AccountInfoNotNil applies the NotNil predicate on the "account_info" field.
func AccountInfoNotNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotNull(FieldAccountInfo))
}

// ProxyInfoIsNil applies the IsNil predicate on the "proxy_info" field.
func ProxyInfoIsNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIsNull(FieldProxyInfo))
}

// ProxyInfoNotNil applies the NotNil predicate on the "proxy_info" field.
func ProxyInfoNotNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotNull(FieldProxyInfo))
}

// CommunicationIsNil applies the IsNil predicate on the "communication" field.
func CommunicationIsNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIsNull(FieldCommunication))
}

// CommunicationNotNil applies the NotNil predicate on the "communication" field.
func CommunicationNotNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotNull(FieldCommunication))
}

// AdminNotesEQ applies the EQ predicate on the "admin_notes" field.
func AdminNotesEQ(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldAdminNotes, v))
}

// AdminNotesNEQ applies the NEQ predicate on the "admin_notes" field.
func AdminNotesNEQ(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNEQ(FieldAdminNotes, v))
}

// AdminNotesIn applies the In predicate on the "admin_notes" field.
func AdminNotesIn(vs ...string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIn(FieldAdminNotes, vs...))
}

// AdminNotesNotIn applies the NotIn predicate on the "admin_notes" field.
func AdminNotesNotIn(vs ...string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotIn(FieldAdminNotes, vs...))
}

// AdminNotesGT applies the GT predicate on the "admin_notes" field.
func AdminNotesGT(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGT(FieldAdminNotes, v))
}

// AdminNotesGTE applies the GTE predicate on the "admin_notes" field.
func AdminNotesGTE(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGTE(FieldAdminNotes, v))
}

// AdminNotesLT applies the LT predicate on the "admin_notes" field.
func AdminNotesLT(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLT(FieldAdminNotes, v))
}

// AdminNotesLTE applies the LTE predicate on the "admin_notes" field.
func AdminNotesLTE(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLTE(FieldAdminNotes, v))
}

// AdminNotesContains applies the Contains predicate on the "admin_notes" field.
func AdminNotesContains(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldContains(FieldAdminNotes, v))
}

// AdminNotesHasPrefix applies the HasPrefix predicate on the "admin_notes" field.
func AdminNotesHasPrefix(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldHasPrefix(FieldAdminNotes, v))
}

// AdminNotesHasSuffix applies the HasSuffix predicate on the "admin_notes" field.
func AdminNotesHasSuffix(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldHasSuffix(FieldAdminNotes, v))
}

// AdminNotesIsNil applies the IsNil predicate on the "admin_notes" field.
func AdminNotesIsNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIsNull(FieldAdminNotes))
}

// AdminNotesNotNil applies the NotNil predicate on the "admin_notes" field.
func AdminNotesNotNil() predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotNull(FieldAdminNotes))
}

// AdminNotesEqualFold applies the EqualFold predicate on the "admin_notes" field.
func AdminNotesEqualFold(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEqualFold(FieldAdminNotes, v))
}

// AdminNotesContainsFold applies the ContainsFold predicate on the "admin_notes" field.
func AdminNotesContainsFold(v string) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldContainsFold(FieldAdminNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasVehicleType applies the HasEdge predicate on the "vehicle_type" edge.
func HasVehicleType() predicate.CarpoolSession {
	return predicate.CarpoolSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, VehicleTypeTable, VehicleTypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVehicleTypeWith applies the HasEdge predicate on the "vehicle_type" edge with a given conditions (other predicates).
func HasVehicleTypeWith(preds ...predicate.CarpoolVehicleType) predicate.CarpoolSession {
	return predicate.CarpoolSession(func(s *sql.Selector) {
		step := newVehicleTypeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParticipants applies the HasEdge predicate on the "participants" edge.
func HasParticipants() predicate.CarpoolSession {
	return predicate.CarpoolSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ParticipantsTable, ParticipantsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParticipantsWith applies the HasEdge predicate on the "participants" edge with a given conditions (other predicates).
func HasParticipantsWith(preds ...predicate.CarpoolParticipant) predicate.CarpoolSession {
	return predicate.CarpoolSession(func(s *sql.Selector) {
		step := newParticipantsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVouchers applies the HasEdge predicate on the "vouchers" edge.
func HasVouchers() predicate.CarpoolSession {
	return predicate.CarpoolSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VouchersTable, VouchersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVouchersWith applies the HasEdge predicate on the "vouchers" edge with a given conditions (other predicates).
func HasVouchersWith(preds ...predicate.CarpoolVoucher) predicate.CarpoolSession {
	return predicate.CarpoolSession(func(s *sql.Selector) {
		step := newVouchersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CarpoolSession) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CarpoolSession) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CarpoolSession) predicate.CarpoolSession {
	return predicate.CarpoolSession(sql.NotPredicates(p))
}
