// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolnoticeversion"
	"github.com/Wei-Shaw/sub2api/ent/carpoolparticipant"
)

// CarpoolNoticeVersionCreate is the builder for creating a CarpoolNoticeVersion entity.
type CarpoolNoticeVersionCreate struct {
	config
	mutation *CarpoolNoticeVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTitle sets the "title" field.
func (_c *CarpoolNoticeVersionCreate) SetTitle(v string) *CarpoolNoticeVersionCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetContentMd sets the "content_md" field.
func (_c *CarpoolNoticeVersionCreate) SetContentMd(v string) *CarpoolNoticeVersionCreate {
	_c.mutation.SetContentMd(v)
	return _c
}

// SetNillableContentMd sets the "content_md" field if the given value is not nil.
func (_c *CarpoolNoticeVersionCreate) SetNillableContentMd(v *string) *CarpoolNoticeVersionCreate {
	if v != nil {
		_c.SetContentMd(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *CarpoolNoticeVersionCreate) SetVersion(v int) *CarpoolNoticeVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *CarpoolNoticeVersionCreate) SetNillableVersion(v *int) *CarpoolNoticeVersionCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *CarpoolNoticeVersionCreate) SetActive(v bool) *CarpoolNoticeVersionCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *CarpoolNoticeVersionCreate) SetNillableActive(v *bool) *CarpoolNoticeVersionCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *CarpoolNoticeVersionCreate) SetPublishedAt(v time.Time) *CarpoolNoticeVersionCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *CarpoolNoticeVersionCreate) SetNillablePublishedAt(v *time.Time) *CarpoolNoticeVersionCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CarpoolNoticeVersionCreate) SetCreatedAt(v time.Time) *CarpoolNoticeVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CarpoolNoticeVersionCreate) SetNillableCreatedAt(v *time.Time) *CarpoolNoticeVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CarpoolNoticeVersionCreate) SetUpdatedAt(v time.Time) *CarpoolNoticeVersionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CarpoolNoticeVersionCreate) SetNillableUpdatedAt(v *time.Time) *CarpoolNoticeVersionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddParticipantIDs adds the "participants" edge to the CarpoolParticipant entity by IDs.
func (_c *CarpoolNoticeVersionCreate) AddParticipantIDs(ids ...int64) *CarpoolNoticeVersionCreate {
	_c.mutation.AddParticipantIDs(ids...)
	return _c
}

// AddParticipants adds the "participants" edges to the CarpoolParticipant entity.
func (_c *CarpoolNoticeVersionCreate) AddParticipants(v ...*CarpoolParticipant) *CarpoolNoticeVersionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddParticipantIDs(ids...)
}

// Mutation returns the CarpoolNoticeVersionMutation object of the builder.
func (_c *CarpoolNoticeVersionCreate) Mutation() *CarpoolNoticeVersionMutation {
	return _c.mutation
}

// Save creates the CarpoolNoticeVersion in the database.
func (_c *CarpoolNoticeVersionCreate) Save(ctx context.Context) (*CarpoolNoticeVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CarpoolNoticeVersionCreate) SaveX(ctx context.Context) *CarpoolNoticeVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolNoticeVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolNoticeVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CarpoolNoticeVersionCreate) defaults() {
	if _, ok := _c.mutation.ContentMd(); !ok {
		v := carpoolnoticeversion.DefaultContentMd
		_c.mutation.SetContentMd(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := carpoolnoticeversion.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := carpoolnoticeversion.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := carpoolnoticeversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := carpoolnoticeversion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CarpoolNoticeVersionCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "CarpoolNoticeVersion.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := carpoolnoticeversion.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CarpoolNoticeVersion.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentMd(); !ok {
		return &ValidationError{Name: "content_md", err: errors.New(`ent: missing required field "CarpoolNoticeVersion.content_md"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "CarpoolNoticeVersion.version"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "CarpoolNoticeVersion.active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CarpoolNoticeVersion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CarpoolNoticeVersion.updated_at"`)}
	}
	return nil
}

func (_c *CarpoolNoticeVersionCreate) sqlSave(ctx context.Context) (*CarpoolNoticeVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CarpoolNoticeVersionCreate) createSpec() (*CarpoolNoticeVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &CarpoolNoticeVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(carpoolnoticeversion.Table, sqlgraph.NewFieldSpec(carpoolnoticeversion.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(carpoolnoticeversion.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.ContentMd(); ok {
		_spec.SetField(carpoolnoticeversion.FieldContentMd, field.TypeString, value)
		_node.ContentMd = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(carpoolnoticeversion.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(carpoolnoticeversion.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(carpoolnoticeversion.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(carpoolnoticeversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(carpoolnoticeversion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ParticipantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolnoticeversion.ParticipantsTable,
			Columns: []string{carpoolnoticeversion.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carpoolparticipant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolNoticeVersion.Create().
//		SetTitle(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolNoticeVersionUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolNoticeVersionCreate) OnConflict(opts ...sql.ConflictOption) *CarpoolNoticeVersionUpsertOne {
	_c.conflict = opts
	return &CarpoolNoticeVersionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolNoticeVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolNoticeVersionCreate) OnConflictColumns(columns ...string) *CarpoolNoticeVersionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolNoticeVersionUpsertOne{
		create: _c,
	}
}

type (
	// CarpoolNoticeVersionUpsertOne is the builder for "upsert"-ing
	//  one CarpoolNoticeVersion node.
	CarpoolNoticeVersionUpsertOne struct {
		create *CarpoolNoticeVersionCreate
	}

	// CarpoolNoticeVersionUpsert is the "OnConflict" setter.
	CarpoolNoticeVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetTitle sets the "title" field.
func (u *CarpoolNoticeVersionUpsert) SetTitle(v string) *CarpoolNoticeVersionUpsert {
	u.Set(carpoolnoticeversion.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsert) UpdateTitle() *CarpoolNoticeVersionUpsert {
	u.SetExcluded(carpoolnoticeversion.FieldTitle)
	return u
}

// SetContentMd sets the "content_md" field.
func (u *CarpoolNoticeVersionUpsert) SetContentMd(v string) *CarpoolNoticeVersionUpsert {
	u.Set(carpoolnoticeversion.FieldContentMd, v)
	return u
}

// UpdateContentMd sets the "content_md" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsert) UpdateContentMd() *CarpoolNoticeVersionUpsert {
	u.SetExcluded(carpoolnoticeversion.FieldContentMd)
	return u
}

// SetVersion sets the "version" field.
func (u *CarpoolNoticeVersionUpsert) SetVersion(v int) *CarpoolNoticeVersionUpsert {
	u.Set(carpoolnoticeversion.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsert) UpdateVersion() *CarpoolNoticeVersionUpsert {
	u.SetExcluded(carpoolnoticeversion.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *CarpoolNoticeVersionUpsert) AddVersion(v int) *CarpoolNoticeVersionUpsert {
	u.Add(carpoolnoticeversion.FieldVersion, v)
	return u
}

// SetActive sets the "active" field.
func (u *CarpoolNoticeVersionUpsert) SetActive(v bool) *CarpoolNoticeVersionUpsert {
	u.Set(carpoolnoticeversion.FieldActive, v)
	return u
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsert) UpdateActive() *CarpoolNoticeVersionUpsert {
	u.SetExcluded(carpoolnoticeversion.FieldActive)
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *CarpoolNoticeVersionUpsert) SetPublishedAt(v time.Time) *CarpoolNoticeVersionUpsert {
	u.Set(carpoolnoticeversion.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsert) UpdatePublishedAt() *CarpoolNoticeVersionUpsert {
	u.SetExcluded(carpoolnoticeversion.FieldPublishedAt)
	return u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *CarpoolNoticeVersionUpsert) ClearPublishedAt() *CarpoolNoticeVersionUpsert {
	u.SetNull(carpoolnoticeversion.FieldPublishedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolNoticeVersionUpsert) SetUpdatedAt(v time.Time) *CarpoolNoticeVersionUpsert {
	u.Set(carpoolnoticeversion.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsert) UpdateUpdatedAt() *CarpoolNoticeVersionUpsert {
	u.SetExcluded(carpoolnoticeversion.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CarpoolNoticeVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolNoticeVersionUpsertOne) UpdateNewValues() *CarpoolNoticeVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(carpoolnoticeversion.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolNoticeVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CarpoolNoticeVersionUpsertOne) Ignore() *CarpoolNoticeVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolNoticeVersionUpsertOne) DoNothing() *CarpoolNoticeVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolNoticeVersionCreate.OnConflict
// documentation for more info.
func (u *CarpoolNoticeVersionUpsertOne) Update(set func(*CarpoolNoticeVersionUpsert)) *CarpoolNoticeVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolNoticeVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *CarpoolNoticeVersionUpsertOne) SetTitle(v string) *CarpoolNoticeVersionUpsertOne {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsertOne) UpdateTitle() *CarpoolNoticeVersionUpsertOne {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.UpdateTitle()
	})
}

// SetContentMd sets the "content_md" field.
func (u *CarpoolNoticeVersionUpsertOne) SetContentMd(v string) *CarpoolNoticeVersionUpsertOne {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.SetContentMd(v)
	})
}

// UpdateContentMd sets the "content_md" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsertOne) UpdateContentMd() *CarpoolNoticeVersionUpsertOne {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.UpdateContentMd()
	})
}

// SetVersion sets the "version" field.
func (u *CarpoolNoticeVersionUpsertOne) SetVersion(v int) *CarpoolNoticeVersionUpsertOne {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *CarpoolNoticeVersionUpsertOne) AddVersion(v int) *CarpoolNoticeVersionUpsertOne {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsertOne) UpdateVersion() *CarpoolNoticeVersionUpsertOne {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.UpdateVersion()
	})
}

// SetActive sets the "active" field.
func (u *CarpoolNoticeVersionUpsertOne) SetActive(v bool) *CarpoolNoticeVersionUpsertOne {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsertOne) UpdateActive() *CarpoolNoticeVersionUpsertOne {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.UpdateActive()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *CarpoolNoticeVersionUpsertOne) SetPublishedAt(v time.Time) *CarpoolNoticeVersionUpsertOne {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsertOne) UpdatePublishedAt() *CarpoolNoticeVersionUpsertOne {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *CarpoolNoticeVersionUpsertOne) ClearPublishedAt() *CarpoolNoticeVersionUpsertOne {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.ClearPublishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolNoticeVersionUpsertOne) SetUpdatedAt(v time.Time) *CarpoolNoticeVersionUpsertOne {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsertOne) UpdateUpdatedAt() *CarpoolNoticeVersionUpsertOne {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CarpoolNoticeVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolNoticeVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolNoticeVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CarpoolNoticeVersionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CarpoolNoticeVersionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CarpoolNoticeVersionCreateBulk is the builder for creating many CarpoolNoticeVersion entities in bulk.
type CarpoolNoticeVersionCreateBulk struct {
	config
	err      error
	builders []*CarpoolNoticeVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the CarpoolNoticeVersion entities in the database.
func (_c *CarpoolNoticeVersionCreateBulk) Save(ctx context.Context) ([]*CarpoolNoticeVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CarpoolNoticeVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CarpoolNoticeVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CarpoolNoticeVersionCreateBulk) SaveX(ctx context.Context) []*CarpoolNoticeVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolNoticeVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolNoticeVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolNoticeVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolNoticeVersionUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolNoticeVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *CarpoolNoticeVersionUpsertBulk {
	_c.conflict = opts
	return &CarpoolNoticeVersionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolNoticeVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolNoticeVersionCreateBulk) OnConflictColumns(columns ...string) *CarpoolNoticeVersionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolNoticeVersionUpsertBulk{
		create: _c,
	}
}

// CarpoolNoticeVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of CarpoolNoticeVersion nodes.
type CarpoolNoticeVersionUpsertBulk struct {
	create *CarpoolNoticeVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CarpoolNoticeVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolNoticeVersionUpsertBulk) UpdateNewValues() *CarpoolNoticeVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(carpoolnoticeversion.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolNoticeVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CarpoolNoticeVersionUpsertBulk) Ignore() *CarpoolNoticeVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolNoticeVersionUpsertBulk) DoNothing() *CarpoolNoticeVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolNoticeVersionCreateBulk.OnConflict
// documentation for more info.
func (u *CarpoolNoticeVersionUpsertBulk) Update(set func(*CarpoolNoticeVersionUpsert)) *CarpoolNoticeVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolNoticeVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *CarpoolNoticeVersionUpsertBulk) SetTitle(v string) *CarpoolNoticeVersionUpsertBulk {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsertBulk) UpdateTitle() *CarpoolNoticeVersionUpsertBulk {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.UpdateTitle()
	})
}

// SetContentMd sets the "content_md" field.
func (u *CarpoolNoticeVersionUpsertBulk) SetContentMd(v string) *CarpoolNoticeVersionUpsertBulk {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.SetContentMd(v)
	})
}

// UpdateContentMd sets the "content_md" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsertBulk) UpdateContentMd() *CarpoolNoticeVersionUpsertBulk {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.UpdateContentMd()
	})
}

// SetVersion sets the "version" field.
func (u *CarpoolNoticeVersionUpsertBulk) SetVersion(v int) *CarpoolNoticeVersionUpsertBulk {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *CarpoolNoticeVersionUpsertBulk) AddVersion(v int) *CarpoolNoticeVersionUpsertBulk {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsertBulk) UpdateVersion() *CarpoolNoticeVersionUpsertBulk {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.UpdateVersion()
	})
}

// SetActive sets the "active" field.
func (u *CarpoolNoticeVersionUpsertBulk) SetActive(v bool) *CarpoolNoticeVersionUpsertBulk {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsertBulk) UpdateActive() *CarpoolNoticeVersionUpsertBulk {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.UpdateActive()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *CarpoolNoticeVersionUpsertBulk) SetPublishedAt(v time.Time) *CarpoolNoticeVersionUpsertBulk {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsertBulk) UpdatePublishedAt() *CarpoolNoticeVersionUpsertBulk {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *CarpoolNoticeVersionUpsertBulk) ClearPublishedAt() *CarpoolNoticeVersionUpsertBulk {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.ClearPublishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolNoticeVersionUpsertBulk) SetUpdatedAt(v time.Time) *CarpoolNoticeVersionUpsertBulk {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolNoticeVersionUpsertBulk) UpdateUpdatedAt() *CarpoolNoticeVersionUpsertBulk {
	return u.Update(func(s *CarpoolNoticeVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CarpoolNoticeVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CarpoolNoticeVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolNoticeVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolNoticeVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
