// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolnoticeversion"
	"github.com/Wei-Shaw/sub2api/ent/carpoolparticipant"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CarpoolNoticeVersionUpdate is the builder for updating CarpoolNoticeVersion entities.
type CarpoolNoticeVersionUpdate struct {
	config
	hooks    []Hook
	mutation *CarpoolNoticeVersionMutation
}

// Where appends a list predicates to the CarpoolNoticeVersionUpdate builder.
func (_u *CarpoolNoticeVersionUpdate) Where(ps ...predicate.CarpoolNoticeVersion) *CarpoolNoticeVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *CarpoolNoticeVersionUpdate) SetTitle(v string) *CarpoolNoticeVersionUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CarpoolNoticeVersionUpdate) SetNillableTitle(v *string) *CarpoolNoticeVersionUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContentMd sets the "content_md" field.
func (_u *CarpoolNoticeVersionUpdate) SetContentMd(v string) *CarpoolNoticeVersionUpdate {
	_u.mutation.SetContentMd(v)
	return _u
}

// SetNillableContentMd sets the "content_md" field if the given value is not nil.
func (_u *CarpoolNoticeVersionUpdate) SetNillableContentMd(v *string) *CarpoolNoticeVersionUpdate {
	if v != nil {
		_u.SetContentMd(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *CarpoolNoticeVersionUpdate) SetVersion(v int) *CarpoolNoticeVersionUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CarpoolNoticeVersionUpdate) SetNillableVersion(v *int) *CarpoolNoticeVersionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *CarpoolNoticeVersionUpdate) AddVersion(v int) *CarpoolNoticeVersionUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *CarpoolNoticeVersionUpdate) SetActive(v bool) *CarpoolNoticeVersionUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *CarpoolNoticeVersionUpdate) SetNillableActive(v *bool) *CarpoolNoticeVersionUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *CarpoolNoticeVersionUpdate) SetPublishedAt(v time.Time) *CarpoolNoticeVersionUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *CarpoolNoticeVersionUpdate) SetNillablePublishedAt(v *time.Time) *CarpoolNoticeVersionUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *CarpoolNoticeVersionUpdate) ClearPublishedAt() *CarpoolNoticeVersionUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CarpoolNoticeVersionUpdate) SetUpdatedAt(v time.Time) *CarpoolNoticeVersionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddParticipantIDs adds the "participants" edge to the CarpoolParticipant entity by IDs.
func (_u *CarpoolNoticeVersionUpdate) AddParticipantIDs(ids ...int64) *CarpoolNoticeVersionUpdate {
	_u.mutation.AddParticipantIDs(ids...)
	return _u
}

// AddParticipants adds the "participants" edges to the CarpoolParticipant entity.
func (_u *CarpoolNoticeVersionUpdate) AddParticipants(v ...*CarpoolParticipant) *CarpoolNoticeVersionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParticipantIDs(ids...)
}

// Mutation returns the CarpoolNoticeVersionMutation object of the builder.
func (_u *CarpoolNoticeVersionUpdate) Mutation() *CarpoolNoticeVersionMutation {
	return _u.mutation
}

// ClearParticipants clears all "participants" edges to the CarpoolParticipant entity.
func (_u *CarpoolNoticeVersionUpdate) ClearParticipants() *CarpoolNoticeVersionUpdate {
	_u.mutation.ClearParticipants()
	return _u
}

// RemoveParticipantIDs removes the "participants" edge to CarpoolParticipant entities by IDs.
func (_u *CarpoolNoticeVersionUpdate) RemoveParticipantIDs(ids ...int64) *CarpoolNoticeVersionUpdate {
	_u.mutation.RemoveParticipantIDs(ids...)
	return _u
}

// RemoveParticipants removes "participants" edges to CarpoolParticipant entities.
func (_u *CarpoolNoticeVersionUpdate) RemoveParticipants(v ...*CarpoolParticipant) *CarpoolNoticeVersionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParticipantIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CarpoolNoticeVersionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CarpoolNoticeVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CarpoolNoticeVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CarpoolNoticeVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CarpoolNoticeVersionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := carpoolnoticeversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CarpoolNoticeVersionUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := carpoolnoticeversion.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CarpoolNoticeVersion.title": %w`, err)}
		}
	}
	return nil
}

func (_u *CarpoolNoticeVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carpoolnoticeversion.Table, carpoolnoticeversion.Columns, sqlgraph.NewFieldSpec(carpoolnoticeversion.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(carpoolnoticeversion.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentMd(); ok {
		_spec.SetField(carpoolnoticeversion.FieldContentMd, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(carpoolnoticeversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(carpoolnoticeversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(carpoolnoticeversion.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(carpoolnoticeversion.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(carpoolnoticeversion.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(carpoolnoticeversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ParticipantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolnoticeversion.ParticipantsTable,
			Columns: []string{carpoolnoticeversion.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carpoolparticipant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParticipantsIDs(); len(nodes) > 0 && !_u.mutation.ParticipantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolnoticeversion.ParticipantsTable,
			Columns: []string{carpoolnoticeversion.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carpoolparticipant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParticipantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolnoticeversion.ParticipantsTable,
			Columns: []string{carpoolnoticeversion.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carpoolparticipant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carpoolnoticeversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CarpoolNoticeVersionUpdateOne is the builder for updating a single CarpoolNoticeVersion entity.
type CarpoolNoticeVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CarpoolNoticeVersionMutation
}

// SetTitle sets the "title" field.
func (_u *CarpoolNoticeVersionUpdateOne) SetTitle(v string) *CarpoolNoticeVersionUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CarpoolNoticeVersionUpdateOne) SetNillableTitle(v *string) *CarpoolNoticeVersionUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContentMd sets the "content_md" field.
func (_u *CarpoolNoticeVersionUpdateOne) SetContentMd(v string) *CarpoolNoticeVersionUpdateOne {
	_u.mutation.SetContentMd(v)
	return _u
}

// SetNillableContentMd sets the "content_md" field if the given value is not nil.
func (_u *CarpoolNoticeVersionUpdateOne) SetNillableContentMd(v *string) *CarpoolNoticeVersionUpdateOne {
	if v != nil {
		_u.SetContentMd(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *CarpoolNoticeVersionUpdateOne) SetVersion(v int) *CarpoolNoticeVersionUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CarpoolNoticeVersionUpdateOne) SetNillableVersion(v *int) *CarpoolNoticeVersionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *CarpoolNoticeVersionUpdateOne) AddVersion(v int) *CarpoolNoticeVersionUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *CarpoolNoticeVersionUpdateOne) SetActive(v bool) *CarpoolNoticeVersionUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *CarpoolNoticeVersionUpdateOne) SetNillableActive(v *bool) *CarpoolNoticeVersionUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *CarpoolNoticeVersionUpdateOne) SetPublishedAt(v time.Time) *CarpoolNoticeVersionUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *CarpoolNoticeVersionUpdateOne) SetNillablePublishedAt(v *time.Time) *CarpoolNoticeVersionUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *CarpoolNoticeVersionUpdateOne) ClearPublishedAt() *CarpoolNoticeVersionUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CarpoolNoticeVersionUpdateOne) SetUpdatedAt(v time.Time) *CarpoolNoticeVersionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddParticipantIDs adds the "participants" edge to the CarpoolParticipant entity by IDs.
func (_u *CarpoolNoticeVersionUpdateOne) AddParticipantIDs(ids ...int64) *CarpoolNoticeVersionUpdateOne {
	_u.mutation.AddParticipantIDs(ids...)
	return _u
}

// AddParticipants adds the "participants" edges to the CarpoolParticipant entity.
func (_u *CarpoolNoticeVersionUpdateOne) AddParticipants(v ...*CarpoolParticipant) *CarpoolNoticeVersionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParticipantIDs(ids...)
}

// Mutation returns the CarpoolNoticeVersionMutation object of the builder.
func (_u *CarpoolNoticeVersionUpdateOne) Mutation() *CarpoolNoticeVersionMutation {
	return _u.mutation
}

// ClearParticipants clears all "participants" edges to the CarpoolParticipant entity.
func (_u *CarpoolNoticeVersionUpdateOne) ClearParticipants() *CarpoolNoticeVersionUpdateOne {
	_u.mutation.ClearParticipants()
	return _u
}

// RemoveParticipantIDs removes the "participants" edge to CarpoolParticipant entities by IDs.
func (_u *CarpoolNoticeVersionUpdateOne) RemoveParticipantIDs(ids ...int64) *CarpoolNoticeVersionUpdateOne {
	_u.mutation.RemoveParticipantIDs(ids...)
	return _u
}

// RemoveParticipants removes "participants" edges to CarpoolParticipant entities.
func (_u *CarpoolNoticeVersionUpdateOne) RemoveParticipants(v ...*CarpoolParticipant) *CarpoolNoticeVersionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParticipantIDs(ids...)
}

// Where appends a list predicates to the CarpoolNoticeVersionUpdate builder.
func (_u *CarpoolNoticeVersionUpdateOne) Where(ps ...predicate.CarpoolNoticeVersion) *CarpoolNoticeVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CarpoolNoticeVersionUpdateOne) Select(field string, fields ...string) *CarpoolNoticeVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CarpoolNoticeVersion entity.
func (_u *CarpoolNoticeVersionUpdateOne) Save(ctx context.Context) (*CarpoolNoticeVersion, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CarpoolNoticeVersionUpdateOne) SaveX(ctx context.Context) *CarpoolNoticeVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CarpoolNoticeVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CarpoolNoticeVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CarpoolNoticeVersionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := carpoolnoticeversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CarpoolNoticeVersionUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := carpoolnoticeversion.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CarpoolNoticeVersion.title": %w`, err)}
		}
	}
	return nil
}

func (_u *CarpoolNoticeVersionUpdateOne) sqlSave(ctx context.Context) (_node *CarpoolNoticeVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carpoolnoticeversion.Table, carpoolnoticeversion.Columns, sqlgraph.NewFieldSpec(carpoolnoticeversion.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CarpoolNoticeVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, carpoolnoticeversion.FieldID)
		for _, f := range fields {
			if !carpoolnoticeversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != carpoolnoticeversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(carpoolnoticeversion.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentMd(); ok {
		_spec.SetField(carpoolnoticeversion.FieldContentMd, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(carpoolnoticeversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(carpoolnoticeversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(carpoolnoticeversion.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(carpoolnoticeversion.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(carpoolnoticeversion.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(carpoolnoticeversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ParticipantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolnoticeversion.ParticipantsTable,
			Columns: []string{carpoolnoticeversion.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carpoolparticipant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParticipantsIDs(); len(nodes) > 0 && !_u.mutation.ParticipantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolnoticeversion.ParticipantsTable,
			Columns: []string{carpoolnoticeversion.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carpoolparticipant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParticipantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolnoticeversion.ParticipantsTable,
			Columns: []string{carpoolnoticeversion.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carpoolparticipant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CarpoolNoticeVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carpoolnoticeversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
