// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolsession"
	"github.com/Wei-Shaw/sub2api/ent/carpoolvoucher"
)

// CarpoolVoucherCreate is the builder for creating a CarpoolVoucher entity.
type CarpoolVoucherCreate struct {
	config
	mutation *CarpoolVoucherMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSessionID sets the "session_id" field.
func (_c *CarpoolVoucherCreate) SetSessionID(v int64) *CarpoolVoucherCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetFileURL sets the "file_url" field.
func (_c *CarpoolVoucherCreate) SetFileURL(v string) *CarpoolVoucherCreate {
	_c.mutation.SetFileURL(v)
	return _c
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_c *CarpoolVoucherCreate) SetNillableFileURL(v *string) *CarpoolVoucherCreate {
	if v != nil {
		_c.SetFileURL(*v)
	}
	return _c
}

// SetFileName sets the "file_name" field.
func (_c *CarpoolVoucherCreate) SetFileName(v string) *CarpoolVoucherCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_c *CarpoolVoucherCreate) SetNillableFileName(v *string) *CarpoolVoucherCreate {
	if v != nil {
		_c.SetFileName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *CarpoolVoucherCreate) SetDescription(v string) *CarpoolVoucherCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CarpoolVoucherCreate) SetNillableDescription(v *string) *CarpoolVoucherCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetUploadedBy sets the "uploaded_by" field.
func (_c *CarpoolVoucherCreate) SetUploadedBy(v int64) *CarpoolVoucherCreate {
	_c.mutation.SetUploadedBy(v)
	return _c
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (_c *CarpoolVoucherCreate) SetNillableUploadedBy(v *int64) *CarpoolVoucherCreate {
	if v != nil {
		_c.SetUploadedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CarpoolVoucherCreate) SetCreatedAt(v time.Time) *CarpoolVoucherCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CarpoolVoucherCreate) SetNillableCreatedAt(v *time.Time) *CarpoolVoucherCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSession sets the "session" edge to the CarpoolSession entity.
func (_c *CarpoolVoucherCreate) SetSession(v *CarpoolSession) *CarpoolVoucherCreate {
	return _c.SetSessionID(v.ID)
}

// Mutation returns the CarpoolVoucherMutation object of the builder.
func (_c *CarpoolVoucherCreate) Mutation() *CarpoolVoucherMutation {
	return _c.mutation
}

// Save creates the CarpoolVoucher in the database.
func (_c *CarpoolVoucherCreate) Save(ctx context.Context) (*CarpoolVoucher, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CarpoolVoucherCreate) SaveX(ctx context.Context) *CarpoolVoucher {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolVoucherCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolVoucherCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CarpoolVoucherCreate) defaults() {
	if _, ok := _c.mutation.FileURL(); !ok {
		v := carpoolvoucher.DefaultFileURL
		_c.mutation.SetFileURL(v)
	}
	if _, ok := _c.mutation.FileName(); !ok {
		v := carpoolvoucher.DefaultFileName
		_c.mutation.SetFileName(v)
	}
	if _, ok := _c.mutation.UploadedBy(); !ok {
		v := carpoolvoucher.DefaultUploadedBy
		_c.mutation.SetUploadedBy(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := carpoolvoucher.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CarpoolVoucherCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "CarpoolVoucher.session_id"`)}
	}
	if _, ok := _c.mutation.FileURL(); !ok {
		return &ValidationError{Name: "file_url", err: errors.New(`ent: missing required field "CarpoolVoucher.file_url"`)}
	}
	if _, ok := _c.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "CarpoolVoucher.file_name"`)}
	}
	if v, ok := _c.mutation.FileName(); ok {
		if err := carpoolvoucher.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "CarpoolVoucher.file_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UploadedBy(); !ok {
		return &ValidationError{Name: "uploaded_by", err: errors.New(`ent: missing required field "CarpoolVoucher.uploaded_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CarpoolVoucher.created_at"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "CarpoolVoucher.session"`)}
	}
	return nil
}

func (_c *CarpoolVoucherCreate) sqlSave(ctx context.Context) (*CarpoolVoucher, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CarpoolVoucherCreate) createSpec() (*CarpoolVoucher, *sqlgraph.CreateSpec) {
	var (
		_node = &CarpoolVoucher{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(carpoolvoucher.Table, sqlgraph.NewFieldSpec(carpoolvoucher.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.FileURL(); ok {
		_spec.SetField(carpoolvoucher.FieldFileURL, field.TypeString, value)
		_node.FileURL = value
	}
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(carpoolvoucher.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(carpoolvoucher.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.UploadedBy(); ok {
		_spec.SetField(carpoolvoucher.FieldUploadedBy, field.TypeInt64, value)
		_node.UploadedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(carpoolvoucher.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   carpoolvoucher.SessionTable,
			Columns: []string{carpoolvoucher.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carpoolsession.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolVoucher.Create().
//		SetSessionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolVoucherUpsert) {
//			SetSessionID(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolVoucherCreate) OnConflict(opts ...sql.ConflictOption) *CarpoolVoucherUpsertOne {
	_c.conflict = opts
	return &CarpoolVoucherUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolVoucher.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolVoucherCreate) OnConflictColumns(columns ...string) *CarpoolVoucherUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolVoucherUpsertOne{
		create: _c,
	}
}

type (
	// CarpoolVoucherUpsertOne is the builder for "upsert"-ing
	//  one CarpoolVoucher node.
	CarpoolVoucherUpsertOne struct {
		create *CarpoolVoucherCreate
	}

	// CarpoolVoucherUpsert is the "OnConflict" setter.
	CarpoolVoucherUpsert struct {
		*sql.UpdateSet
	}
)

// SetSessionID sets the "session_id" field.
func (u *CarpoolVoucherUpsert) SetSessionID(v int64) *CarpoolVoucherUpsert {
	u.Set(carpoolvoucher.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *CarpoolVoucherUpsert) UpdateSessionID() *CarpoolVoucherUpsert {
	u.SetExcluded(carpoolvoucher.FieldSessionID)
	return u
}

// SetFileURL sets the "file_url" field.
func (u *CarpoolVoucherUpsert) SetFileURL(v string) *CarpoolVoucherUpsert {
	u.Set(carpoolvoucher.FieldFileURL, v)
	return u
}

// UpdateFileURL sets the "file_url" field to the value that was provided on create.
func (u *CarpoolVoucherUpsert) UpdateFileURL() *CarpoolVoucherUpsert {
	u.SetExcluded(carpoolvoucher.FieldFileURL)
	return u
}

// SetFileName sets the "file_name" field.
func (u *CarpoolVoucherUpsert) SetFileName(v string) *CarpoolVoucherUpsert {
	u.Set(carpoolvoucher.FieldFileName, v)
	return u
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *CarpoolVoucherUpsert) UpdateFileName() *CarpoolVoucherUpsert {
	u.SetExcluded(carpoolvoucher.FieldFileName)
	return u
}

// SetDescription sets the "description" field.
func (u *CarpoolVoucherUpsert) SetDescription(v string) *CarpoolVoucherUpsert {
	u.Set(carpoolvoucher.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CarpoolVoucherUpsert) UpdateDescription() *CarpoolVoucherUpsert {
	u.SetExcluded(carpoolvoucher.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *CarpoolVoucherUpsert) ClearDescription() *CarpoolVoucherUpsert {
	u.SetNull(carpoolvoucher.FieldDescription)
	return u
}

// SetUploadedBy sets the "uploaded_by" field.
func (u *CarpoolVoucherUpsert) SetUploadedBy(v int64) *CarpoolVoucherUpsert {
	u.Set(carpoolvoucher.FieldUploadedBy, v)
	return u
}

// UpdateUploadedBy sets the "uploaded_by" field to the value that was provided on create.
func (u *CarpoolVoucherUpsert) UpdateUploadedBy() *CarpoolVoucherUpsert {
	u.SetExcluded(carpoolvoucher.FieldUploadedBy)
	return u
}

// AddUploadedBy adds v to the "uploaded_by" field.
func (u *CarpoolVoucherUpsert) AddUploadedBy(v int64) *CarpoolVoucherUpsert {
	u.Add(carpoolvoucher.FieldUploadedBy, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CarpoolVoucher.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolVoucherUpsertOne) UpdateNewValues() *CarpoolVoucherUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(carpoolvoucher.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolVoucher.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CarpoolVoucherUpsertOne) Ignore() *CarpoolVoucherUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolVoucherUpsertOne) DoNothing() *CarpoolVoucherUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolVoucherCreate.OnConflict
// documentation for more info.
func (u *CarpoolVoucherUpsertOne) Update(set func(*CarpoolVoucherUpsert)) *CarpoolVoucherUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolVoucherUpsert{UpdateSet: update})
	}))
	return u
}

// SetSessionID sets the "session_id" field.
func (u *CarpoolVoucherUpsertOne) SetSessionID(v int64) *CarpoolVoucherUpsertOne {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *CarpoolVoucherUpsertOne) UpdateSessionID() *CarpoolVoucherUpsertOne {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.UpdateSessionID()
	})
}

// SetFileURL sets the "file_url" field.
func (u *CarpoolVoucherUpsertOne) SetFileURL(v string) *CarpoolVoucherUpsertOne {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.SetFileURL(v)
	})
}

// UpdateFileURL sets the "file_url" field to the value that was provided on create.
func (u *CarpoolVoucherUpsertOne) UpdateFileURL() *CarpoolVoucherUpsertOne {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.UpdateFileURL()
	})
}

// SetFileName sets the "file_name" field.
func (u *CarpoolVoucherUpsertOne) SetFileName(v string) *CarpoolVoucherUpsertOne {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *CarpoolVoucherUpsertOne) UpdateFileName() *CarpoolVoucherUpsertOne {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.UpdateFileName()
	})
}

// SetDescription sets the "description" field.
func (u *CarpoolVoucherUpsertOne) SetDescription(v string) *CarpoolVoucherUpsertOne {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CarpoolVoucherUpsertOne) UpdateDescription() *CarpoolVoucherUpsertOne {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *CarpoolVoucherUpsertOne) ClearDescription() *CarpoolVoucherUpsertOne {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.ClearDescription()
	})
}

// SetUploadedBy sets the "uploaded_by" field.
func (u *CarpoolVoucherUpsertOne) SetUploadedBy(v int64) *CarpoolVoucherUpsertOne {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.SetUploadedBy(v)
	})
}

// AddUploadedBy adds v to the "uploaded_by" field.
func (u *CarpoolVoucherUpsertOne) AddUploadedBy(v int64) *CarpoolVoucherUpsertOne {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.AddUploadedBy(v)
	})
}

// UpdateUploadedBy sets the "uploaded_by" field to the value that was provided on create.
func (u *CarpoolVoucherUpsertOne) UpdateUploadedBy() *CarpoolVoucherUpsertOne {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.UpdateUploadedBy()
	})
}

// Exec executes the query.
func (u *CarpoolVoucherUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolVoucherCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolVoucherUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CarpoolVoucherUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CarpoolVoucherUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CarpoolVoucherCreateBulk is the builder for creating many CarpoolVoucher entities in bulk.
type CarpoolVoucherCreateBulk struct {
	config
	err      error
	builders []*CarpoolVoucherCreate
	conflict []sql.ConflictOption
}

// Save creates the CarpoolVoucher entities in the database.
func (_c *CarpoolVoucherCreateBulk) Save(ctx context.Context) ([]*CarpoolVoucher, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CarpoolVoucher, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CarpoolVoucherMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CarpoolVoucherCreateBulk) SaveX(ctx context.Context) []*CarpoolVoucher {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolVoucherCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolVoucherCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolVoucher.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolVoucherUpsert) {
//			SetSessionID(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolVoucherCreateBulk) OnConflict(opts ...sql.ConflictOption) *CarpoolVoucherUpsertBulk {
	_c.conflict = opts
	return &CarpoolVoucherUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolVoucher.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolVoucherCreateBulk) OnConflictColumns(columns ...string) *CarpoolVoucherUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolVoucherUpsertBulk{
		create: _c,
	}
}

// CarpoolVoucherUpsertBulk is the builder for "upsert"-ing
// a bulk of CarpoolVoucher nodes.
type CarpoolVoucherUpsertBulk struct {
	create *CarpoolVoucherCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CarpoolVoucher.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolVoucherUpsertBulk) UpdateNewValues() *CarpoolVoucherUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(carpoolvoucher.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolVoucher.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CarpoolVoucherUpsertBulk) Ignore() *CarpoolVoucherUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolVoucherUpsertBulk) DoNothing() *CarpoolVoucherUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolVoucherCreateBulk.OnConflict
// documentation for more info.
func (u *CarpoolVoucherUpsertBulk) Update(set func(*CarpoolVoucherUpsert)) *CarpoolVoucherUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolVoucherUpsert{UpdateSet: update})
	}))
	return u
}

// SetSessionID sets the "session_id" field.
func (u *CarpoolVoucherUpsertBulk) SetSessionID(v int64) *CarpoolVoucherUpsertBulk {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *CarpoolVoucherUpsertBulk) UpdateSessionID() *CarpoolVoucherUpsertBulk {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.UpdateSessionID()
	})
}

// SetFileURL sets the "file_url" field.
func (u *CarpoolVoucherUpsertBulk) SetFileURL(v string) *CarpoolVoucherUpsertBulk {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.SetFileURL(v)
	})
}

// UpdateFileURL sets the "file_url" field to the value that was provided on create.
func (u *CarpoolVoucherUpsertBulk) UpdateFileURL() *CarpoolVoucherUpsertBulk {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.UpdateFileURL()
	})
}

// SetFileName sets the "file_name" field.
func (u *CarpoolVoucherUpsertBulk) SetFileName(v string) *CarpoolVoucherUpsertBulk {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *CarpoolVoucherUpsertBulk) UpdateFileName() *CarpoolVoucherUpsertBulk {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.UpdateFileName()
	})
}

// SetDescription sets the "description" field.
func (u *CarpoolVoucherUpsertBulk) SetDescription(v string) *CarpoolVoucherUpsertBulk {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CarpoolVoucherUpsertBulk) UpdateDescription() *CarpoolVoucherUpsertBulk {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *CarpoolVoucherUpsertBulk) ClearDescription() *CarpoolVoucherUpsertBulk {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.ClearDescription()
	})
}

// SetUploadedBy sets the "uploaded_by" field.
func (u *CarpoolVoucherUpsertBulk) SetUploadedBy(v int64) *CarpoolVoucherUpsertBulk {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.SetUploadedBy(v)
	})
}

// AddUploadedBy adds v to the "uploaded_by" field.
func (u *CarpoolVoucherUpsertBulk) AddUploadedBy(v int64) *CarpoolVoucherUpsertBulk {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.AddUploadedBy(v)
	})
}

// UpdateUploadedBy sets the "uploaded_by" field to the value that was provided on create.
func (u *CarpoolVoucherUpsertBulk) UpdateUploadedBy() *CarpoolVoucherUpsertBulk {
	return u.Update(func(s *CarpoolVoucherUpsert) {
		s.UpdateUploadedBy()
	})
}

// Exec executes the query.
func (u *CarpoolVoucherUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CarpoolVoucherCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolVoucherCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolVoucherUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
