// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/carpoolsession"
	"github.com/Wei-Shaw/sub2api/ent/carpoolvehicletype"
)

// CarpoolSession is the model entity for the CarpoolSession schema.
type CarpoolSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// VehicleTypeID holds the value of the "vehicle_type_id" field.
	VehicleTypeID int64 `json:"vehicle_type_id,omitempty"`
	// SessionNo holds the value of the "session_no" field.
	SessionNo string `json:"session_no,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// SeatCount holds the value of the "seat_count" field.
	SeatCount int `json:"seat_count,omitempty"`
	// PaidCount holds the value of the "paid_count" field.
	PaidCount int `json:"paid_count,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FilledAt holds the value of the "filled_at" field.
	FilledAt *time.Time `json:"filled_at,omitempty"`
	// ProvisionedAt holds the value of the "provisioned_at" field.
	ProvisionedAt *time.Time `json:"provisioned_at,omitempty"`
	// ServiceStartedAt holds the value of the "service_started_at" field.
	ServiceStartedAt *time.Time `json:"service_started_at,omitempty"`
	// ServiceEndedAt holds the value of the "service_ended_at" field.
	ServiceEndedAt *time.Time `json:"service_ended_at,omitempty"`
	// AccountInfo holds the value of the "account_info" field.
	AccountInfo map[string]interface{} `json:"account_info,omitempty"`
	// ProxyInfo holds the value of the "proxy_info" field.
	ProxyInfo map[string]interface{} `json:"proxy_info,omitempty"`
	// Communication holds the value of the "communication" field.
	Communication map[string]interface{} `json:"communication,omitempty"`
	// AdminNotes holds the value of the "admin_notes" field.
	AdminNotes *string `json:"admin_notes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CarpoolSessionQuery when eager-loading is set.
	Edges        CarpoolSessionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CarpoolSessionEdges holds the relations/edges for other nodes in the graph.
type CarpoolSessionEdges struct {
	// VehicleType holds the value of the vehicle_type edge.
	VehicleType *CarpoolVehicleType `json:"vehicle_type,omitempty"`
	// Participants holds the value of the participants edge.
	Participants []*CarpoolParticipant `json:"participants,omitempty"`
	// Vouchers holds the value of the vouchers edge.
	Vouchers []*CarpoolVoucher `json:"vouchers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// VehicleTypeOrErr returns the VehicleType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CarpoolSessionEdges) VehicleTypeOrErr() (*CarpoolVehicleType, error) {
	if e.VehicleType != nil {
		return e.VehicleType, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: carpoolvehicletype.Label}
	}
	return nil, &NotLoadedError{edge: "vehicle_type"}
}

// ParticipantsOrErr returns the Participants value or an error if the edge
// was not loaded in eager-loading.
func (e CarpoolSessionEdges) ParticipantsOrErr() ([]*CarpoolParticipant, error) {
	if e.loadedTypes[1] {
		return e.Participants, nil
	}
	return nil, &NotLoadedError{edge: "participants"}
}

// VouchersOrErr returns the Vouchers value or an error if the edge
// was not loaded in eager-loading.
func (e CarpoolSessionEdges) VouchersOrErr() ([]*CarpoolVoucher, error) {
	if e.loadedTypes[2] {
		return e.Vouchers, nil
	}
	return nil, &NotLoadedError{edge: "vouchers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CarpoolSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case carpoolsession.FieldAccountInfo, carpoolsession.FieldProxyInfo, carpoolsession.FieldCommunication:
			values[i] = new([]byte)
		case carpoolsession.FieldID, carpoolsession.FieldVehicleTypeID, carpoolsession.FieldSeatCount, carpoolsession.FieldPaidCount:
			values[i] = new(sql.NullInt64)
		case carpoolsession.FieldSessionNo, carpoolsession.FieldStatus, carpoolsession.FieldAdminNotes:
			values[i] = new(sql.NullString)
		case carpoolsession.FieldStartedAt, carpoolsession.FieldFilledAt, carpoolsession.FieldProvisionedAt, carpoolsession.FieldServiceStartedAt, carpoolsession.FieldServiceEndedAt, carpoolsession.FieldCreatedAt, carpoolsession.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CarpoolSession fields.
func (_m *CarpoolSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case carpoolsession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case carpoolsession.FieldVehicleTypeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field vehicle_type_id", values[i])
			} else if value.Valid {
				_m.VehicleTypeID = value.Int64
			}
		case carpoolsession.FieldSessionNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_no", values[i])
			} else if value.Valid {
				_m.SessionNo = value.String
			}
		case carpoolsession.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case carpoolsession.FieldSeatCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field seat_count", values[i])
			} else if value.Valid {
				_m.SeatCount = int(value.Int64)
			}
		case carpoolsession.FieldPaidCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field paid_count", values[i])
			} else if value.Valid {
				_m.PaidCount = int(value.Int64)
			}
		case carpoolsession.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case carpoolsession.FieldFilledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field filled_at", values[i])
			} else if value.Valid {
				_m.FilledAt = new(time.Time)
				*_m.FilledAt = value.Time
			}
		case carpoolsession.FieldProvisionedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field provisioned_at", values[i])
			} else if value.Valid {
				_m.ProvisionedAt = new(time.Time)
				*_m.ProvisionedAt = value.Time
			}
		case carpoolsession.FieldServiceStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field service_started_at", values[i])
			} else if value.Valid {
				_m.ServiceStartedAt = new(time.Time)
				*_m.ServiceStartedAt = value.Time
			}
		case carpoolsession.FieldServiceEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field service_ended_at", values[i])
			} else if value.Valid {
				_m.ServiceEndedAt = new(time.Time)
				*_m.ServiceEndedAt = value.Time
			}
		case carpoolsession.FieldAccountInfo:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field account_info", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AccountInfo); err != nil {
					return fmt.Errorf("unmarshal field account_info: %w", err)
				}
			}
		case carpoolsession.FieldProxyInfo:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_info", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ProxyInfo); err != nil {
					return fmt.Errorf("unmarshal field proxy_info: %w", err)
				}
			}
		case carpoolsession.FieldCommunication:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field communication", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Communication); err != nil {
					return fmt.Errorf("unmarshal field communication: %w", err)
				}
			}
		case carpoolsession.FieldAdminNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field admin_notes", values[i])
			} else if value.Valid {
				_m.AdminNotes = new(string)
				*_m.AdminNotes = value.String
			}
		case carpoolsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case carpoolsession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CarpoolSession.
// This includes values selected through modifiers, order, etc.
func (_m *CarpoolSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryVehicleType queries the "vehicle_type" edge of the CarpoolSession entity.
func (_m *CarpoolSession) QueryVehicleType() *CarpoolVehicleTypeQuery {
	return NewCarpoolSessionClient(_m.config).QueryVehicleType(_m)
}

// QueryParticipants queries the "participants" edge of the CarpoolSession entity.
func (_m *CarpoolSession) QueryParticipants() *CarpoolParticipantQuery {
	return NewCarpoolSessionClient(_m.config).QueryParticipants(_m)
}

// QueryVouchers queries the "vouchers" edge of the CarpoolSession entity.
func (_m *CarpoolSession) QueryVouchers() *CarpoolVoucherQuery {
	return NewCarpoolSessionClient(_m.config).QueryVouchers(_m)
}

// Update returns a builder for updating this CarpoolSession.
// Note that you need to call CarpoolSession.Unwrap() before calling this method if this CarpoolSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CarpoolSession) Update() *CarpoolSessionUpdateOne {
	return NewCarpoolSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CarpoolSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CarpoolSession) Unwrap() *CarpoolSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CarpoolSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CarpoolSession) String() string {
	var builder strings.Builder
	builder.WriteString("CarpoolSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("vehicle_type_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.VehicleTypeID))
	builder.WriteString(", ")
	builder.WriteString("session_no=")
	builder.WriteString(_m.SessionNo)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("seat_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SeatCount))
	builder.WriteString(", ")
	builder.WriteString("paid_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaidCount))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FilledAt; v != nil {
		builder.WriteString("filled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ProvisionedAt; v != nil {
		builder.WriteString("provisioned_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ServiceStartedAt; v != nil {
		builder.WriteString("service_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ServiceEndedAt; v != nil {
		builder.WriteString("service_ended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("account_info=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountInfo))
	builder.WriteString(", ")
	builder.WriteString("proxy_info=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProxyInfo))
	builder.WriteString(", ")
	builder.WriteString("communication=")
	builder.WriteString(fmt.Sprintf("%v", _m.Communication))
	builder.WriteString(", ")
	if v := _m.AdminNotes; v != nil {
		builder.WriteString("admin_notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CarpoolSessions is a parsable slice of CarpoolSession.
type CarpoolSessions []*CarpoolSession
