// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolparticipant"
	"github.com/Wei-Shaw/sub2api/ent/carpoolsession"
	"github.com/Wei-Shaw/sub2api/ent/carpoolvehicletype"
)

// CarpoolVehicleTypeCreate is the builder for creating a CarpoolVehicleType entity.
type CarpoolVehicleTypeCreate struct {
	config
	mutation *CarpoolVehicleTypeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProduct sets the "product" field.
func (_c *CarpoolVehicleTypeCreate) SetProduct(v string) *CarpoolVehicleTypeCreate {
	_c.mutation.SetProduct(v)
	return _c
}

// SetNillableProduct sets the "product" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillableProduct(v *string) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetProduct(*v)
	}
	return _c
}

// SetPlanTier sets the "plan_tier" field.
func (_c *CarpoolVehicleTypeCreate) SetPlanTier(v string) *CarpoolVehicleTypeCreate {
	_c.mutation.SetPlanTier(v)
	return _c
}

// SetNillablePlanTier sets the "plan_tier" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillablePlanTier(v *string) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetPlanTier(*v)
	}
	return _c
}

// SetMultiplier sets the "multiplier" field.
func (_c *CarpoolVehicleTypeCreate) SetMultiplier(v string) *CarpoolVehicleTypeCreate {
	_c.mutation.SetMultiplier(v)
	return _c
}

// SetNillableMultiplier sets the "multiplier" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillableMultiplier(v *string) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetMultiplier(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *CarpoolVehicleTypeCreate) SetName(v string) *CarpoolVehicleTypeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSeatCount sets the "seat_count" field.
func (_c *CarpoolVehicleTypeCreate) SetSeatCount(v int) *CarpoolVehicleTypeCreate {
	_c.mutation.SetSeatCount(v)
	return _c
}

// SetNillableSeatCount sets the "seat_count" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillableSeatCount(v *int) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetSeatCount(*v)
	}
	return _c
}

// SetTotalPrice sets the "total_price" field.
func (_c *CarpoolVehicleTypeCreate) SetTotalPrice(v float64) *CarpoolVehicleTypeCreate {
	_c.mutation.SetTotalPrice(v)
	return _c
}

// SetNillableTotalPrice sets the "total_price" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillableTotalPrice(v *float64) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetTotalPrice(*v)
	}
	return _c
}

// SetUnitPrice sets the "unit_price" field.
func (_c *CarpoolVehicleTypeCreate) SetUnitPrice(v float64) *CarpoolVehicleTypeCreate {
	_c.mutation.SetUnitPrice(v)
	return _c
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillableUnitPrice(v *float64) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetUnitPrice(*v)
	}
	return _c
}

// SetServiceDays sets the "service_days" field.
func (_c *CarpoolVehicleTypeCreate) SetServiceDays(v int) *CarpoolVehicleTypeCreate {
	_c.mutation.SetServiceDays(v)
	return _c
}

// SetNillableServiceDays sets the "service_days" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillableServiceDays(v *int) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetServiceDays(*v)
	}
	return _c
}

// SetRefundWaitHours sets the "refund_wait_hours" field.
func (_c *CarpoolVehicleTypeCreate) SetRefundWaitHours(v int) *CarpoolVehicleTypeCreate {
	_c.mutation.SetRefundWaitHours(v)
	return _c
}

// SetNillableRefundWaitHours sets the "refund_wait_hours" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillableRefundWaitHours(v *int) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetRefundWaitHours(*v)
	}
	return _c
}

// SetCompletedBaseCount sets the "completed_base_count" field.
func (_c *CarpoolVehicleTypeCreate) SetCompletedBaseCount(v int) *CarpoolVehicleTypeCreate {
	_c.mutation.SetCompletedBaseCount(v)
	return _c
}

// SetNillableCompletedBaseCount sets the "completed_base_count" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillableCompletedBaseCount(v *int) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetCompletedBaseCount(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *CarpoolVehicleTypeCreate) SetEnabled(v bool) *CarpoolVehicleTypeCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillableEnabled(v *bool) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSupportRevenuePool sets the "support_revenue_pool" field.
func (_c *CarpoolVehicleTypeCreate) SetSupportRevenuePool(v bool) *CarpoolVehicleTypeCreate {
	_c.mutation.SetSupportRevenuePool(v)
	return _c
}

// SetNillableSupportRevenuePool sets the "support_revenue_pool" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillableSupportRevenuePool(v *bool) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetSupportRevenuePool(*v)
	}
	return _c
}

// SetRequireStaticIP sets the "require_static_ip" field.
func (_c *CarpoolVehicleTypeCreate) SetRequireStaticIP(v bool) *CarpoolVehicleTypeCreate {
	_c.mutation.SetRequireStaticIP(v)
	return _c
}

// SetNillableRequireStaticIP sets the "require_static_ip" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillableRequireStaticIP(v *bool) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetRequireStaticIP(*v)
	}
	return _c
}

// SetWaitDurationOptions sets the "wait_duration_options" field.
func (_c *CarpoolVehicleTypeCreate) SetWaitDurationOptions(v []int) *CarpoolVehicleTypeCreate {
	_c.mutation.SetWaitDurationOptions(v)
	return _c
}

// SetRefundMethods sets the "refund_methods" field.
func (_c *CarpoolVehicleTypeCreate) SetRefundMethods(v []string) *CarpoolVehicleTypeCreate {
	_c.mutation.SetRefundMethods(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *CarpoolVehicleTypeCreate) SetDescription(v string) *CarpoolVehicleTypeCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillableDescription(v *string) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *CarpoolVehicleTypeCreate) SetSortOrder(v int) *CarpoolVehicleTypeCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillableSortOrder(v *int) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CarpoolVehicleTypeCreate) SetCreatedAt(v time.Time) *CarpoolVehicleTypeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillableCreatedAt(v *time.Time) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CarpoolVehicleTypeCreate) SetUpdatedAt(v time.Time) *CarpoolVehicleTypeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CarpoolVehicleTypeCreate) SetNillableUpdatedAt(v *time.Time) *CarpoolVehicleTypeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddSessionIDs adds the "sessions" edge to the CarpoolSession entity by IDs.
func (_c *CarpoolVehicleTypeCreate) AddSessionIDs(ids ...int64) *CarpoolVehicleTypeCreate {
	_c.mutation.AddSessionIDs(ids...)
	return _c
}

// AddSessions adds the "sessions" edges to the CarpoolSession entity.
func (_c *CarpoolVehicleTypeCreate) AddSessions(v ...*CarpoolSession) *CarpoolVehicleTypeCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSessionIDs(ids...)
}

// AddParticipantIDs adds the "participants" edge to the CarpoolParticipant entity by IDs.
func (_c *CarpoolVehicleTypeCreate) AddParticipantIDs(ids ...int64) *CarpoolVehicleTypeCreate {
	_c.mutation.AddParticipantIDs(ids...)
	return _c
}

// AddParticipants adds the "participants" edges to the CarpoolParticipant entity.
func (_c *CarpoolVehicleTypeCreate) AddParticipants(v ...*CarpoolParticipant) *CarpoolVehicleTypeCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddParticipantIDs(ids...)
}

// Mutation returns the CarpoolVehicleTypeMutation object of the builder.
func (_c *CarpoolVehicleTypeCreate) Mutation() *CarpoolVehicleTypeMutation {
	return _c.mutation
}

// Save creates the CarpoolVehicleType in the database.
func (_c *CarpoolVehicleTypeCreate) Save(ctx context.Context) (*CarpoolVehicleType, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CarpoolVehicleTypeCreate) SaveX(ctx context.Context) *CarpoolVehicleType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolVehicleTypeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolVehicleTypeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CarpoolVehicleTypeCreate) defaults() {
	if _, ok := _c.mutation.Product(); !ok {
		v := carpoolvehicletype.DefaultProduct
		_c.mutation.SetProduct(v)
	}
	if _, ok := _c.mutation.PlanTier(); !ok {
		v := carpoolvehicletype.DefaultPlanTier
		_c.mutation.SetPlanTier(v)
	}
	if _, ok := _c.mutation.Multiplier(); !ok {
		v := carpoolvehicletype.DefaultMultiplier
		_c.mutation.SetMultiplier(v)
	}
	if _, ok := _c.mutation.SeatCount(); !ok {
		v := carpoolvehicletype.DefaultSeatCount
		_c.mutation.SetSeatCount(v)
	}
	if _, ok := _c.mutation.TotalPrice(); !ok {
		v := carpoolvehicletype.DefaultTotalPrice
		_c.mutation.SetTotalPrice(v)
	}
	if _, ok := _c.mutation.UnitPrice(); !ok {
		v := carpoolvehicletype.DefaultUnitPrice
		_c.mutation.SetUnitPrice(v)
	}
	if _, ok := _c.mutation.ServiceDays(); !ok {
		v := carpoolvehicletype.DefaultServiceDays
		_c.mutation.SetServiceDays(v)
	}
	if _, ok := _c.mutation.RefundWaitHours(); !ok {
		v := carpoolvehicletype.DefaultRefundWaitHours
		_c.mutation.SetRefundWaitHours(v)
	}
	if _, ok := _c.mutation.CompletedBaseCount(); !ok {
		v := carpoolvehicletype.DefaultCompletedBaseCount
		_c.mutation.SetCompletedBaseCount(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := carpoolvehicletype.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SupportRevenuePool(); !ok {
		v := carpoolvehicletype.DefaultSupportRevenuePool
		_c.mutation.SetSupportRevenuePool(v)
	}
	if _, ok := _c.mutation.RequireStaticIP(); !ok {
		v := carpoolvehicletype.DefaultRequireStaticIP
		_c.mutation.SetRequireStaticIP(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := carpoolvehicletype.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := carpoolvehicletype.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := carpoolvehicletype.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := carpoolvehicletype.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CarpoolVehicleTypeCreate) check() error {
	if _, ok := _c.mutation.Product(); !ok {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required field "CarpoolVehicleType.product"`)}
	}
	if v, ok := _c.mutation.Product(); ok {
		if err := carpoolvehicletype.ProductValidator(v); err != nil {
			return &ValidationError{Name: "product", err: fmt.Errorf(`ent: validator failed for field "CarpoolVehicleType.product": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlanTier(); !ok {
		return &ValidationError{Name: "plan_tier", err: errors.New(`ent: missing required field "CarpoolVehicleType.plan_tier"`)}
	}
	if v, ok := _c.mutation.PlanTier(); ok {
		if err := carpoolvehicletype.PlanTierValidator(v); err != nil {
			return &ValidationError{Name: "plan_tier", err: fmt.Errorf(`ent: validator failed for field "CarpoolVehicleType.plan_tier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Multiplier(); !ok {
		return &ValidationError{Name: "multiplier", err: errors.New(`ent: missing required field "CarpoolVehicleType.multiplier"`)}
	}
	if v, ok := _c.mutation.Multiplier(); ok {
		if err := carpoolvehicletype.MultiplierValidator(v); err != nil {
			return &ValidationError{Name: "multiplier", err: fmt.Errorf(`ent: validator failed for field "CarpoolVehicleType.multiplier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CarpoolVehicleType.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := carpoolvehicletype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CarpoolVehicleType.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SeatCount(); !ok {
		return &ValidationError{Name: "seat_count", err: errors.New(`ent: missing required field "CarpoolVehicleType.seat_count"`)}
	}
	if _, ok := _c.mutation.TotalPrice(); !ok {
		return &ValidationError{Name: "total_price", err: errors.New(`ent: missing required field "CarpoolVehicleType.total_price"`)}
	}
	if _, ok := _c.mutation.UnitPrice(); !ok {
		return &ValidationError{Name: "unit_price", err: errors.New(`ent: missing required field "CarpoolVehicleType.unit_price"`)}
	}
	if _, ok := _c.mutation.ServiceDays(); !ok {
		return &ValidationError{Name: "service_days", err: errors.New(`ent: missing required field "CarpoolVehicleType.service_days"`)}
	}
	if _, ok := _c.mutation.RefundWaitHours(); !ok {
		return &ValidationError{Name: "refund_wait_hours", err: errors.New(`ent: missing required field "CarpoolVehicleType.refund_wait_hours"`)}
	}
	if _, ok := _c.mutation.CompletedBaseCount(); !ok {
		return &ValidationError{Name: "completed_base_count", err: errors.New(`ent: missing required field "CarpoolVehicleType.completed_base_count"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "CarpoolVehicleType.enabled"`)}
	}
	if _, ok := _c.mutation.SupportRevenuePool(); !ok {
		return &ValidationError{Name: "support_revenue_pool", err: errors.New(`ent: missing required field "CarpoolVehicleType.support_revenue_pool"`)}
	}
	if _, ok := _c.mutation.RequireStaticIP(); !ok {
		return &ValidationError{Name: "require_static_ip", err: errors.New(`ent: missing required field "CarpoolVehicleType.require_static_ip"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "CarpoolVehicleType.description"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "CarpoolVehicleType.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CarpoolVehicleType.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CarpoolVehicleType.updated_at"`)}
	}
	return nil
}

func (_c *CarpoolVehicleTypeCreate) sqlSave(ctx context.Context) (*CarpoolVehicleType, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CarpoolVehicleTypeCreate) createSpec() (*CarpoolVehicleType, *sqlgraph.CreateSpec) {
	var (
		_node = &CarpoolVehicleType{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(carpoolvehicletype.Table, sqlgraph.NewFieldSpec(carpoolvehicletype.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Product(); ok {
		_spec.SetField(carpoolvehicletype.FieldProduct, field.TypeString, value)
		_node.Product = value
	}
	if value, ok := _c.mutation.PlanTier(); ok {
		_spec.SetField(carpoolvehicletype.FieldPlanTier, field.TypeString, value)
		_node.PlanTier = value
	}
	if value, ok := _c.mutation.Multiplier(); ok {
		_spec.SetField(carpoolvehicletype.FieldMultiplier, field.TypeString, value)
		_node.Multiplier = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(carpoolvehicletype.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SeatCount(); ok {
		_spec.SetField(carpoolvehicletype.FieldSeatCount, field.TypeInt, value)
		_node.SeatCount = value
	}
	if value, ok := _c.mutation.TotalPrice(); ok {
		_spec.SetField(carpoolvehicletype.FieldTotalPrice, field.TypeFloat64, value)
		_node.TotalPrice = value
	}
	if value, ok := _c.mutation.UnitPrice(); ok {
		_spec.SetField(carpoolvehicletype.FieldUnitPrice, field.TypeFloat64, value)
		_node.UnitPrice = value
	}
	if value, ok := _c.mutation.ServiceDays(); ok {
		_spec.SetField(carpoolvehicletype.FieldServiceDays, field.TypeInt, value)
		_node.ServiceDays = value
	}
	if value, ok := _c.mutation.RefundWaitHours(); ok {
		_spec.SetField(carpoolvehicletype.FieldRefundWaitHours, field.TypeInt, value)
		_node.RefundWaitHours = value
	}
	if value, ok := _c.mutation.CompletedBaseCount(); ok {
		_spec.SetField(carpoolvehicletype.FieldCompletedBaseCount, field.TypeInt, value)
		_node.CompletedBaseCount = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(carpoolvehicletype.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.SupportRevenuePool(); ok {
		_spec.SetField(carpoolvehicletype.FieldSupportRevenuePool, field.TypeBool, value)
		_node.SupportRevenuePool = value
	}
	if value, ok := _c.mutation.RequireStaticIP(); ok {
		_spec.SetField(carpoolvehicletype.FieldRequireStaticIP, field.TypeBool, value)
		_node.RequireStaticIP = value
	}
	if value, ok := _c.mutation.WaitDurationOptions(); ok {
		_spec.SetField(carpoolvehicletype.FieldWaitDurationOptions, field.TypeJSON, value)
		_node.WaitDurationOptions = value
	}
	if value, ok := _c.mutation.RefundMethods(); ok {
		_spec.SetField(carpoolvehicletype.FieldRefundMethods, field.TypeJSON, value)
		_node.RefundMethods = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(carpoolvehicletype.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(carpoolvehicletype.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(carpoolvehicletype.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(carpoolvehicletype.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolvehicletype.SessionsTable,
			Columns: []string{carpoolvehicletype.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carpoolsession.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParticipantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carpoolvehicletype.ParticipantsTable,
			Columns: []string{carpoolvehicletype.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carpoolparticipant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolVehicleType.Create().
//		SetProduct(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolVehicleTypeUpsert) {
//			SetProduct(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolVehicleTypeCreate) OnConflict(opts ...sql.ConflictOption) *CarpoolVehicleTypeUpsertOne {
	_c.conflict = opts
	return &CarpoolVehicleTypeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolVehicleType.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolVehicleTypeCreate) OnConflictColumns(columns ...string) *CarpoolVehicleTypeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolVehicleTypeUpsertOne{
		create: _c,
	}
}

type (
	// CarpoolVehicleTypeUpsertOne is the builder for "upsert"-ing
	//  one CarpoolVehicleType node.
	CarpoolVehicleTypeUpsertOne struct {
		create *CarpoolVehicleTypeCreate
	}

	// CarpoolVehicleTypeUpsert is the "OnConflict" setter.
	CarpoolVehicleTypeUpsert struct {
		*sql.UpdateSet
	}
)

// SetProduct sets the "product" field.
func (u *CarpoolVehicleTypeUpsert) SetProduct(v string) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldProduct, v)
	return u
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateProduct() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldProduct)
	return u
}

// SetPlanTier sets the "plan_tier" field.
func (u *CarpoolVehicleTypeUpsert) SetPlanTier(v string) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldPlanTier, v)
	return u
}

// UpdatePlanTier sets the "plan_tier" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdatePlanTier() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldPlanTier)
	return u
}

// SetMultiplier sets the "multiplier" field.
func (u *CarpoolVehicleTypeUpsert) SetMultiplier(v string) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldMultiplier, v)
	return u
}

// UpdateMultiplier sets the "multiplier" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateMultiplier() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldMultiplier)
	return u
}

// SetName sets the "name" field.
func (u *CarpoolVehicleTypeUpsert) SetName(v string) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateName() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldName)
	return u
}

// SetSeatCount sets the "seat_count" field.
func (u *CarpoolVehicleTypeUpsert) SetSeatCount(v int) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldSeatCount, v)
	return u
}

// UpdateSeatCount sets the "seat_count" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateSeatCount() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldSeatCount)
	return u
}

// AddSeatCount adds v to the "seat_count" field.
func (u *CarpoolVehicleTypeUpsert) AddSeatCount(v int) *CarpoolVehicleTypeUpsert {
	u.Add(carpoolvehicletype.FieldSeatCount, v)
	return u
}

// SetTotalPrice sets the "total_price" field.
func (u *CarpoolVehicleTypeUpsert) SetTotalPrice(v float64) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldTotalPrice, v)
	return u
}

// UpdateTotalPrice sets the "total_price" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateTotalPrice() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldTotalPrice)
	return u
}

// AddTotalPrice adds v to the "total_price" field.
func (u *CarpoolVehicleTypeUpsert) AddTotalPrice(v float64) *CarpoolVehicleTypeUpsert {
	u.Add(carpoolvehicletype.FieldTotalPrice, v)
	return u
}

// SetUnitPrice sets the "unit_price" field.
func (u *CarpoolVehicleTypeUpsert) SetUnitPrice(v float64) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldUnitPrice, v)
	return u
}

// UpdateUnitPrice sets the "unit_price" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateUnitPrice() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldUnitPrice)
	return u
}

// AddUnitPrice adds v to the "unit_price" field.
func (u *CarpoolVehicleTypeUpsert) AddUnitPrice(v float64) *CarpoolVehicleTypeUpsert {
	u.Add(carpoolvehicletype.FieldUnitPrice, v)
	return u
}

// SetServiceDays sets the "service_days" field.
func (u *CarpoolVehicleTypeUpsert) SetServiceDays(v int) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldServiceDays, v)
	return u
}

// UpdateServiceDays sets the "service_days" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateServiceDays() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldServiceDays)
	return u
}

// AddServiceDays adds v to the "service_days" field.
func (u *CarpoolVehicleTypeUpsert) AddServiceDays(v int) *CarpoolVehicleTypeUpsert {
	u.Add(carpoolvehicletype.FieldServiceDays, v)
	return u
}

// SetRefundWaitHours sets the "refund_wait_hours" field.
func (u *CarpoolVehicleTypeUpsert) SetRefundWaitHours(v int) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldRefundWaitHours, v)
	return u
}

// UpdateRefundWaitHours sets the "refund_wait_hours" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateRefundWaitHours() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldRefundWaitHours)
	return u
}

// AddRefundWaitHours adds v to the "refund_wait_hours" field.
func (u *CarpoolVehicleTypeUpsert) AddRefundWaitHours(v int) *CarpoolVehicleTypeUpsert {
	u.Add(carpoolvehicletype.FieldRefundWaitHours, v)
	return u
}

// SetCompletedBaseCount sets the "completed_base_count" field.
func (u *CarpoolVehicleTypeUpsert) SetCompletedBaseCount(v int) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldCompletedBaseCount, v)
	return u
}

// UpdateCompletedBaseCount sets the "completed_base_count" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateCompletedBaseCount() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldCompletedBaseCount)
	return u
}

// AddCompletedBaseCount adds v to the "completed_base_count" field.
func (u *CarpoolVehicleTypeUpsert) AddCompletedBaseCount(v int) *CarpoolVehicleTypeUpsert {
	u.Add(carpoolvehicletype.FieldCompletedBaseCount, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *CarpoolVehicleTypeUpsert) SetEnabled(v bool) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateEnabled() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldEnabled)
	return u
}

// SetSupportRevenuePool sets the "support_revenue_pool" field.
func (u *CarpoolVehicleTypeUpsert) SetSupportRevenuePool(v bool) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldSupportRevenuePool, v)
	return u
}

// UpdateSupportRevenuePool sets the "support_revenue_pool" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateSupportRevenuePool() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldSupportRevenuePool)
	return u
}

// SetRequireStaticIP sets the "require_static_ip" field.
func (u *CarpoolVehicleTypeUpsert) SetRequireStaticIP(v bool) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldRequireStaticIP, v)
	return u
}

// UpdateRequireStaticIP sets the "require_static_ip" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateRequireStaticIP() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldRequireStaticIP)
	return u
}

// SetWaitDurationOptions sets the "wait_duration_options" field.
func (u *CarpoolVehicleTypeUpsert) SetWaitDurationOptions(v []int) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldWaitDurationOptions, v)
	return u
}

// UpdateWaitDurationOptions sets the "wait_duration_options" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateWaitDurationOptions() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldWaitDurationOptions)
	return u
}

// ClearWaitDurationOptions clears the value of the "wait_duration_options" field.
func (u *CarpoolVehicleTypeUpsert) ClearWaitDurationOptions() *CarpoolVehicleTypeUpsert {
	u.SetNull(carpoolvehicletype.FieldWaitDurationOptions)
	return u
}

// SetRefundMethods sets the "refund_methods" field.
func (u *CarpoolVehicleTypeUpsert) SetRefundMethods(v []string) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldRefundMethods, v)
	return u
}

// UpdateRefundMethods sets the "refund_methods" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateRefundMethods() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldRefundMethods)
	return u
}

// ClearRefundMethods clears the value of the "refund_methods" field.
func (u *CarpoolVehicleTypeUpsert) ClearRefundMethods() *CarpoolVehicleTypeUpsert {
	u.SetNull(carpoolvehicletype.FieldRefundMethods)
	return u
}

// SetDescription sets the "description" field.
func (u *CarpoolVehicleTypeUpsert) SetDescription(v string) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateDescription() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldDescription)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *CarpoolVehicleTypeUpsert) SetSortOrder(v int) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateSortOrder() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CarpoolVehicleTypeUpsert) AddSortOrder(v int) *CarpoolVehicleTypeUpsert {
	u.Add(carpoolvehicletype.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolVehicleTypeUpsert) SetUpdatedAt(v time.Time) *CarpoolVehicleTypeUpsert {
	u.Set(carpoolvehicletype.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsert) UpdateUpdatedAt() *CarpoolVehicleTypeUpsert {
	u.SetExcluded(carpoolvehicletype.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CarpoolVehicleType.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolVehicleTypeUpsertOne) UpdateNewValues() *CarpoolVehicleTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(carpoolvehicletype.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolVehicleType.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CarpoolVehicleTypeUpsertOne) Ignore() *CarpoolVehicleTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolVehicleTypeUpsertOne) DoNothing() *CarpoolVehicleTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolVehicleTypeCreate.OnConflict
// documentation for more info.
func (u *CarpoolVehicleTypeUpsertOne) Update(set func(*CarpoolVehicleTypeUpsert)) *CarpoolVehicleTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolVehicleTypeUpsert{UpdateSet: update})
	}))
	return u
}

// SetProduct sets the "product" field.
func (u *CarpoolVehicleTypeUpsertOne) SetProduct(v string) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetProduct(v)
	})
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateProduct() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateProduct()
	})
}

// SetPlanTier sets the "plan_tier" field.
func (u *CarpoolVehicleTypeUpsertOne) SetPlanTier(v string) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetPlanTier(v)
	})
}

// UpdatePlanTier sets the "plan_tier" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdatePlanTier() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdatePlanTier()
	})
}

// SetMultiplier sets the "multiplier" field.
func (u *CarpoolVehicleTypeUpsertOne) SetMultiplier(v string) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetMultiplier(v)
	})
}

// UpdateMultiplier sets the "multiplier" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateMultiplier() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateMultiplier()
	})
}

// SetName sets the "name" field.
func (u *CarpoolVehicleTypeUpsertOne) SetName(v string) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateName() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateName()
	})
}

// SetSeatCount sets the "seat_count" field.
func (u *CarpoolVehicleTypeUpsertOne) SetSeatCount(v int) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetSeatCount(v)
	})
}

// AddSeatCount adds v to the "seat_count" field.
func (u *CarpoolVehicleTypeUpsertOne) AddSeatCount(v int) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.AddSeatCount(v)
	})
}

// UpdateSeatCount sets the "seat_count" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateSeatCount() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateSeatCount()
	})
}

// SetTotalPrice sets the "total_price" field.
func (u *CarpoolVehicleTypeUpsertOne) SetTotalPrice(v float64) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetTotalPrice(v)
	})
}

// AddTotalPrice adds v to the "total_price" field.
func (u *CarpoolVehicleTypeUpsertOne) AddTotalPrice(v float64) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.AddTotalPrice(v)
	})
}

// UpdateTotalPrice sets the "total_price" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateTotalPrice() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateTotalPrice()
	})
}

// SetUnitPrice sets the "unit_price" field.
func (u *CarpoolVehicleTypeUpsertOne) SetUnitPrice(v float64) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetUnitPrice(v)
	})
}

// AddUnitPrice adds v to the "unit_price" field.
func (u *CarpoolVehicleTypeUpsertOne) AddUnitPrice(v float64) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.AddUnitPrice(v)
	})
}

// UpdateUnitPrice sets the "unit_price" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateUnitPrice() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateUnitPrice()
	})
}

// SetServiceDays sets the "service_days" field.
func (u *CarpoolVehicleTypeUpsertOne) SetServiceDays(v int) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetServiceDays(v)
	})
}

// AddServiceDays adds v to the "service_days" field.
func (u *CarpoolVehicleTypeUpsertOne) AddServiceDays(v int) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.AddServiceDays(v)
	})
}

// UpdateServiceDays sets the "service_days" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateServiceDays() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateServiceDays()
	})
}

// SetRefundWaitHours sets the "refund_wait_hours" field.
func (u *CarpoolVehicleTypeUpsertOne) SetRefundWaitHours(v int) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetRefundWaitHours(v)
	})
}

// AddRefundWaitHours adds v to the "refund_wait_hours" field.
func (u *CarpoolVehicleTypeUpsertOne) AddRefundWaitHours(v int) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.AddRefundWaitHours(v)
	})
}

// UpdateRefundWaitHours sets the "refund_wait_hours" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateRefundWaitHours() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateRefundWaitHours()
	})
}

// SetCompletedBaseCount sets the "completed_base_count" field.
func (u *CarpoolVehicleTypeUpsertOne) SetCompletedBaseCount(v int) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetCompletedBaseCount(v)
	})
}

// AddCompletedBaseCount adds v to the "completed_base_count" field.
func (u *CarpoolVehicleTypeUpsertOne) AddCompletedBaseCount(v int) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.AddCompletedBaseCount(v)
	})
}

// UpdateCompletedBaseCount sets the "completed_base_count" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateCompletedBaseCount() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateCompletedBaseCount()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CarpoolVehicleTypeUpsertOne) SetEnabled(v bool) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateEnabled() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateEnabled()
	})
}

// SetSupportRevenuePool sets the "support_revenue_pool" field.
func (u *CarpoolVehicleTypeUpsertOne) SetSupportRevenuePool(v bool) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetSupportRevenuePool(v)
	})
}

// UpdateSupportRevenuePool sets the "support_revenue_pool" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateSupportRevenuePool() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateSupportRevenuePool()
	})
}

// SetRequireStaticIP sets the "require_static_ip" field.
func (u *CarpoolVehicleTypeUpsertOne) SetRequireStaticIP(v bool) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetRequireStaticIP(v)
	})
}

// UpdateRequireStaticIP sets the "require_static_ip" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateRequireStaticIP() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateRequireStaticIP()
	})
}

// SetWaitDurationOptions sets the "wait_duration_options" field.
func (u *CarpoolVehicleTypeUpsertOne) SetWaitDurationOptions(v []int) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetWaitDurationOptions(v)
	})
}

// UpdateWaitDurationOptions sets the "wait_duration_options" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateWaitDurationOptions() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateWaitDurationOptions()
	})
}

// ClearWaitDurationOptions clears the value of the "wait_duration_options" field.
func (u *CarpoolVehicleTypeUpsertOne) ClearWaitDurationOptions() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.ClearWaitDurationOptions()
	})
}

// SetRefundMethods sets the "refund_methods" field.
func (u *CarpoolVehicleTypeUpsertOne) SetRefundMethods(v []string) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetRefundMethods(v)
	})
}

// UpdateRefundMethods sets the "refund_methods" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateRefundMethods() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateRefundMethods()
	})
}

// ClearRefundMethods clears the value of the "refund_methods" field.
func (u *CarpoolVehicleTypeUpsertOne) ClearRefundMethods() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.ClearRefundMethods()
	})
}

// SetDescription sets the "description" field.
func (u *CarpoolVehicleTypeUpsertOne) SetDescription(v string) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateDescription() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateDescription()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CarpoolVehicleTypeUpsertOne) SetSortOrder(v int) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CarpoolVehicleTypeUpsertOne) AddSortOrder(v int) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateSortOrder() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolVehicleTypeUpsertOne) SetUpdatedAt(v time.Time) *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertOne) UpdateUpdatedAt() *CarpoolVehicleTypeUpsertOne {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CarpoolVehicleTypeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolVehicleTypeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolVehicleTypeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CarpoolVehicleTypeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CarpoolVehicleTypeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CarpoolVehicleTypeCreateBulk is the builder for creating many CarpoolVehicleType entities in bulk.
type CarpoolVehicleTypeCreateBulk struct {
	config
	err      error
	builders []*CarpoolVehicleTypeCreate
	conflict []sql.ConflictOption
}

// Save creates the CarpoolVehicleType entities in the database.
func (_c *CarpoolVehicleTypeCreateBulk) Save(ctx context.Context) ([]*CarpoolVehicleType, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CarpoolVehicleType, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CarpoolVehicleTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CarpoolVehicleTypeCreateBulk) SaveX(ctx context.Context) []*CarpoolVehicleType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarpoolVehicleTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarpoolVehicleTypeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarpoolVehicleType.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarpoolVehicleTypeUpsert) {
//			SetProduct(v+v).
//		}).
//		Exec(ctx)
func (_c *CarpoolVehicleTypeCreateBulk) OnConflict(opts ...sql.ConflictOption) *CarpoolVehicleTypeUpsertBulk {
	_c.conflict = opts
	return &CarpoolVehicleTypeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarpoolVehicleType.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarpoolVehicleTypeCreateBulk) OnConflictColumns(columns ...string) *CarpoolVehicleTypeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarpoolVehicleTypeUpsertBulk{
		create: _c,
	}
}

// CarpoolVehicleTypeUpsertBulk is the builder for "upsert"-ing
// a bulk of CarpoolVehicleType nodes.
type CarpoolVehicleTypeUpsertBulk struct {
	create *CarpoolVehicleTypeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CarpoolVehicleType.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CarpoolVehicleTypeUpsertBulk) UpdateNewValues() *CarpoolVehicleTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(carpoolvehicletype.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarpoolVehicleType.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CarpoolVehicleTypeUpsertBulk) Ignore() *CarpoolVehicleTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarpoolVehicleTypeUpsertBulk) DoNothing() *CarpoolVehicleTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarpoolVehicleTypeCreateBulk.OnConflict
// documentation for more info.
func (u *CarpoolVehicleTypeUpsertBulk) Update(set func(*CarpoolVehicleTypeUpsert)) *CarpoolVehicleTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarpoolVehicleTypeUpsert{UpdateSet: update})
	}))
	return u
}

// SetProduct sets the "product" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetProduct(v string) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetProduct(v)
	})
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateProduct() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateProduct()
	})
}

// SetPlanTier sets the "plan_tier" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetPlanTier(v string) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetPlanTier(v)
	})
}

// UpdatePlanTier sets the "plan_tier" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdatePlanTier() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdatePlanTier()
	})
}

// SetMultiplier sets the "multiplier" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetMultiplier(v string) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetMultiplier(v)
	})
}

// UpdateMultiplier sets the "multiplier" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateMultiplier() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateMultiplier()
	})
}

// SetName sets the "name" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetName(v string) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateName() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateName()
	})
}

// SetSeatCount sets the "seat_count" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetSeatCount(v int) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetSeatCount(v)
	})
}

// AddSeatCount adds v to the "seat_count" field.
func (u *CarpoolVehicleTypeUpsertBulk) AddSeatCount(v int) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.AddSeatCount(v)
	})
}

// UpdateSeatCount sets the "seat_count" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateSeatCount() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateSeatCount()
	})
}

// SetTotalPrice sets the "total_price" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetTotalPrice(v float64) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetTotalPrice(v)
	})
}

// AddTotalPrice adds v to the "total_price" field.
func (u *CarpoolVehicleTypeUpsertBulk) AddTotalPrice(v float64) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.AddTotalPrice(v)
	})
}

// UpdateTotalPrice sets the "total_price" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateTotalPrice() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateTotalPrice()
	})
}

// SetUnitPrice sets the "unit_price" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetUnitPrice(v float64) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetUnitPrice(v)
	})
}

// AddUnitPrice adds v to the "unit_price" field.
func (u *CarpoolVehicleTypeUpsertBulk) AddUnitPrice(v float64) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.AddUnitPrice(v)
	})
}

// UpdateUnitPrice sets the "unit_price" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateUnitPrice() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateUnitPrice()
	})
}

// SetServiceDays sets the "service_days" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetServiceDays(v int) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetServiceDays(v)
	})
}

// AddServiceDays adds v to the "service_days" field.
func (u *CarpoolVehicleTypeUpsertBulk) AddServiceDays(v int) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.AddServiceDays(v)
	})
}

// UpdateServiceDays sets the "service_days" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateServiceDays() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateServiceDays()
	})
}

// SetRefundWaitHours sets the "refund_wait_hours" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetRefundWaitHours(v int) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetRefundWaitHours(v)
	})
}

// AddRefundWaitHours adds v to the "refund_wait_hours" field.
func (u *CarpoolVehicleTypeUpsertBulk) AddRefundWaitHours(v int) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.AddRefundWaitHours(v)
	})
}

// UpdateRefundWaitHours sets the "refund_wait_hours" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateRefundWaitHours() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateRefundWaitHours()
	})
}

// SetCompletedBaseCount sets the "completed_base_count" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetCompletedBaseCount(v int) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetCompletedBaseCount(v)
	})
}

// AddCompletedBaseCount adds v to the "completed_base_count" field.
func (u *CarpoolVehicleTypeUpsertBulk) AddCompletedBaseCount(v int) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.AddCompletedBaseCount(v)
	})
}

// UpdateCompletedBaseCount sets the "completed_base_count" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateCompletedBaseCount() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateCompletedBaseCount()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetEnabled(v bool) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateEnabled() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateEnabled()
	})
}

// SetSupportRevenuePool sets the "support_revenue_pool" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetSupportRevenuePool(v bool) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetSupportRevenuePool(v)
	})
}

// UpdateSupportRevenuePool sets the "support_revenue_pool" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateSupportRevenuePool() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateSupportRevenuePool()
	})
}

// SetRequireStaticIP sets the "require_static_ip" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetRequireStaticIP(v bool) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetRequireStaticIP(v)
	})
}

// UpdateRequireStaticIP sets the "require_static_ip" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateRequireStaticIP() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateRequireStaticIP()
	})
}

// SetWaitDurationOptions sets the "wait_duration_options" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetWaitDurationOptions(v []int) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetWaitDurationOptions(v)
	})
}

// UpdateWaitDurationOptions sets the "wait_duration_options" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateWaitDurationOptions() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateWaitDurationOptions()
	})
}

// ClearWaitDurationOptions clears the value of the "wait_duration_options" field.
func (u *CarpoolVehicleTypeUpsertBulk) ClearWaitDurationOptions() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.ClearWaitDurationOptions()
	})
}

// SetRefundMethods sets the "refund_methods" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetRefundMethods(v []string) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetRefundMethods(v)
	})
}

// UpdateRefundMethods sets the "refund_methods" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateRefundMethods() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateRefundMethods()
	})
}

// ClearRefundMethods clears the value of the "refund_methods" field.
func (u *CarpoolVehicleTypeUpsertBulk) ClearRefundMethods() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.ClearRefundMethods()
	})
}

// SetDescription sets the "description" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetDescription(v string) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateDescription() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateDescription()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetSortOrder(v int) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CarpoolVehicleTypeUpsertBulk) AddSortOrder(v int) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateSortOrder() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarpoolVehicleTypeUpsertBulk) SetUpdatedAt(v time.Time) *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarpoolVehicleTypeUpsertBulk) UpdateUpdatedAt() *CarpoolVehicleTypeUpsertBulk {
	return u.Update(func(s *CarpoolVehicleTypeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CarpoolVehicleTypeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CarpoolVehicleTypeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarpoolVehicleTypeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarpoolVehicleTypeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
