// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolparticipant"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CarpoolParticipantDelete is the builder for deleting a CarpoolParticipant entity.
type CarpoolParticipantDelete struct {
	config
	hooks    []Hook
	mutation *CarpoolParticipantMutation
}

// Where appends a list predicates to the CarpoolParticipantDelete builder.
func (_d *CarpoolParticipantDelete) Where(ps ...predicate.CarpoolParticipant) *CarpoolParticipantDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CarpoolParticipantDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CarpoolParticipantDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CarpoolParticipantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(carpoolparticipant.Table, sqlgraph.NewFieldSpec(carpoolparticipant.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CarpoolParticipantDeleteOne is the builder for deleting a single CarpoolParticipant entity.
type CarpoolParticipantDeleteOne struct {
	_d *CarpoolParticipantDelete
}

// Where appends a list predicates to the CarpoolParticipantDelete builder.
func (_d *CarpoolParticipantDeleteOne) Where(ps ...predicate.CarpoolParticipant) *CarpoolParticipantDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CarpoolParticipantDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{carpoolparticipant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CarpoolParticipantDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
