// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/carpoolsession"
	"github.com/Wei-Shaw/sub2api/ent/carpoolvoucher"
)

// CarpoolVoucher is the model entity for the CarpoolVoucher schema.
type CarpoolVoucher struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID int64 `json:"session_id,omitempty"`
	// FileURL holds the value of the "file_url" field.
	FileURL string `json:"file_url,omitempty"`
	// FileName holds the value of the "file_name" field.
	FileName string `json:"file_name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// UploadedBy holds the value of the "uploaded_by" field.
	UploadedBy int64 `json:"uploaded_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CarpoolVoucherQuery when eager-loading is set.
	Edges        CarpoolVoucherEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CarpoolVoucherEdges holds the relations/edges for other nodes in the graph.
type CarpoolVoucherEdges struct {
	// Session holds the value of the session edge.
	Session *CarpoolSession `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CarpoolVoucherEdges) SessionOrErr() (*CarpoolSession, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: carpoolsession.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CarpoolVoucher) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case carpoolvoucher.FieldID, carpoolvoucher.FieldSessionID, carpoolvoucher.FieldUploadedBy:
			values[i] = new(sql.NullInt64)
		case carpoolvoucher.FieldFileURL, carpoolvoucher.FieldFileName, carpoolvoucher.FieldDescription:
			values[i] = new(sql.NullString)
		case carpoolvoucher.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CarpoolVoucher fields.
func (_m *CarpoolVoucher) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case carpoolvoucher.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case carpoolvoucher.FieldSessionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.Int64
			}
		case carpoolvoucher.FieldFileURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_url", values[i])
			} else if value.Valid {
				_m.FileURL = value.String
			}
		case carpoolvoucher.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				_m.FileName = value.String
			}
		case carpoolvoucher.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case carpoolvoucher.FieldUploadedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uploaded_by", values[i])
			} else if value.Valid {
				_m.UploadedBy = value.Int64
			}
		case carpoolvoucher.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CarpoolVoucher.
// This includes values selected through modifiers, order, etc.
func (_m *CarpoolVoucher) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the CarpoolVoucher entity.
func (_m *CarpoolVoucher) QuerySession() *CarpoolSessionQuery {
	return NewCarpoolVoucherClient(_m.config).QuerySession(_m)
}

// Update returns a builder for updating this CarpoolVoucher.
// Note that you need to call CarpoolVoucher.Unwrap() before calling this method if this CarpoolVoucher
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CarpoolVoucher) Update() *CarpoolVoucherUpdateOne {
	return NewCarpoolVoucherClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CarpoolVoucher entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CarpoolVoucher) Unwrap() *CarpoolVoucher {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CarpoolVoucher is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CarpoolVoucher) String() string {
	var builder strings.Builder
	builder.WriteString("CarpoolVoucher(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionID))
	builder.WriteString(", ")
	builder.WriteString("file_url=")
	builder.WriteString(_m.FileURL)
	builder.WriteString(", ")
	builder.WriteString("file_name=")
	builder.WriteString(_m.FileName)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("uploaded_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UploadedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CarpoolVouchers is a parsable slice of CarpoolVoucher.
type CarpoolVouchers []*CarpoolVoucher
