// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/carpoolvoucher"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CarpoolVoucherDelete is the builder for deleting a CarpoolVoucher entity.
type CarpoolVoucherDelete struct {
	config
	hooks    []Hook
	mutation *CarpoolVoucherMutation
}

// Where appends a list predicates to the CarpoolVoucherDelete builder.
func (_d *CarpoolVoucherDelete) Where(ps ...predicate.CarpoolVoucher) *CarpoolVoucherDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CarpoolVoucherDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CarpoolVoucherDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CarpoolVoucherDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(carpoolvoucher.Table, sqlgraph.NewFieldSpec(carpoolvoucher.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CarpoolVoucherDeleteOne is the builder for deleting a single CarpoolVoucher entity.
type CarpoolVoucherDeleteOne struct {
	_d *CarpoolVoucherDelete
}

// Where appends a list predicates to the CarpoolVoucherDelete builder.
func (_d *CarpoolVoucherDeleteOne) Where(ps ...predicate.CarpoolVoucher) *CarpoolVoucherDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CarpoolVoucherDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{carpoolvoucher.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CarpoolVoucherDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
