// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterychance"
	"github.com/Wei-Shaw/sub2api/ent/lotterydrawrecord"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprize"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// LotteryDrawRecordCreate is the builder for creating a LotteryDrawRecord entity.
type LotteryDrawRecordCreate struct {
	config
	mutation *LotteryDrawRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *LotteryDrawRecordCreate) SetUserID(v int64) *LotteryDrawRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetChanceID sets the "chance_id" field.
func (_c *LotteryDrawRecordCreate) SetChanceID(v int64) *LotteryDrawRecordCreate {
	_c.mutation.SetChanceID(v)
	return _c
}

// SetPrizeID sets the "prize_id" field.
func (_c *LotteryDrawRecordCreate) SetPrizeID(v int64) *LotteryDrawRecordCreate {
	_c.mutation.SetPrizeID(v)
	return _c
}

// SetPrizeName sets the "prize_name" field.
func (_c *LotteryDrawRecordCreate) SetPrizeName(v string) *LotteryDrawRecordCreate {
	_c.mutation.SetPrizeName(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *LotteryDrawRecordCreate) SetAmount(v float64) *LotteryDrawRecordCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *LotteryDrawRecordCreate) SetNillableAmount(v *float64) *LotteryDrawRecordCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetBalanceBefore sets the "balance_before" field.
func (_c *LotteryDrawRecordCreate) SetBalanceBefore(v float64) *LotteryDrawRecordCreate {
	_c.mutation.SetBalanceBefore(v)
	return _c
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_c *LotteryDrawRecordCreate) SetNillableBalanceBefore(v *float64) *LotteryDrawRecordCreate {
	if v != nil {
		_c.SetBalanceBefore(*v)
	}
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *LotteryDrawRecordCreate) SetBalanceAfter(v float64) *LotteryDrawRecordCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_c *LotteryDrawRecordCreate) SetNillableBalanceAfter(v *float64) *LotteryDrawRecordCreate {
	if v != nil {
		_c.SetBalanceAfter(*v)
	}
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *LotteryDrawRecordCreate) SetSourceType(v string) *LotteryDrawRecordCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetConfigSnapshot sets the "config_snapshot" field.
func (_c *LotteryDrawRecordCreate) SetConfigSnapshot(v map[string]interface{}) *LotteryDrawRecordCreate {
	_c.mutation.SetConfigSnapshot(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryDrawRecordCreate) SetCreatedAt(v time.Time) *LotteryDrawRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryDrawRecordCreate) SetNillableCreatedAt(v *time.Time) *LotteryDrawRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *LotteryDrawRecordCreate) SetUser(v *User) *LotteryDrawRecordCreate {
	return _c.SetUserID(v.ID)
}

// SetChance sets the "chance" edge to the LotteryChance entity.
func (_c *LotteryDrawRecordCreate) SetChance(v *LotteryChance) *LotteryDrawRecordCreate {
	return _c.SetChanceID(v.ID)
}

// SetPrize sets the "prize" edge to the LotteryPrize entity.
func (_c *LotteryDrawRecordCreate) SetPrize(v *LotteryPrize) *LotteryDrawRecordCreate {
	return _c.SetPrizeID(v.ID)
}

// Mutation returns the LotteryDrawRecordMutation object of the builder.
func (_c *LotteryDrawRecordCreate) Mutation() *LotteryDrawRecordMutation {
	return _c.mutation
}

// Save creates the LotteryDrawRecord in the database.
func (_c *LotteryDrawRecordCreate) Save(ctx context.Context) (*LotteryDrawRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryDrawRecordCreate) SaveX(ctx context.Context) *LotteryDrawRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryDrawRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryDrawRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryDrawRecordCreate) defaults() {
	if _, ok := _c.mutation.Amount(); !ok {
		v := lotterydrawrecord.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.BalanceBefore(); !ok {
		v := lotterydrawrecord.DefaultBalanceBefore
		_c.mutation.SetBalanceBefore(v)
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		v := lotterydrawrecord.DefaultBalanceAfter
		_c.mutation.SetBalanceAfter(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotterydrawrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryDrawRecordCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LotteryDrawRecord.user_id"`)}
	}
	if _, ok := _c.mutation.ChanceID(); !ok {
		return &ValidationError{Name: "chance_id", err: errors.New(`ent: missing required field "LotteryDrawRecord.chance_id"`)}
	}
	if _, ok := _c.mutation.PrizeID(); !ok {
		return &ValidationError{Name: "prize_id", err: errors.New(`ent: missing required field "LotteryDrawRecord.prize_id"`)}
	}
	if _, ok := _c.mutation.PrizeName(); !ok {
		return &ValidationError{Name: "prize_name", err: errors.New(`ent: missing required field "LotteryDrawRecord.prize_name"`)}
	}
	if v, ok := _c.mutation.PrizeName(); ok {
		if err := lotterydrawrecord.PrizeNameValidator(v); err != nil {
			return &ValidationError{Name: "prize_name", err: fmt.Errorf(`ent: validator failed for field "LotteryDrawRecord.prize_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "LotteryDrawRecord.amount"`)}
	}
	if _, ok := _c.mutation.BalanceBefore(); !ok {
		return &ValidationError{Name: "balance_before", err: errors.New(`ent: missing required field "LotteryDrawRecord.balance_before"`)}
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "LotteryDrawRecord.balance_after"`)}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "LotteryDrawRecord.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := lotterydrawrecord.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "LotteryDrawRecord.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryDrawRecord.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "LotteryDrawRecord.user"`)}
	}
	if len(_c.mutation.ChanceIDs()) == 0 {
		return &ValidationError{Name: "chance", err: errors.New(`ent: missing required edge "LotteryDrawRecord.chance"`)}
	}
	if len(_c.mutation.PrizeIDs()) == 0 {
		return &ValidationError{Name: "prize", err: errors.New(`ent: missing required edge "LotteryDrawRecord.prize"`)}
	}
	return nil
}

func (_c *LotteryDrawRecordCreate) sqlSave(ctx context.Context) (*LotteryDrawRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryDrawRecordCreate) createSpec() (*LotteryDrawRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryDrawRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotterydrawrecord.Table, sqlgraph.NewFieldSpec(lotterydrawrecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.PrizeName(); ok {
		_spec.SetField(lotterydrawrecord.FieldPrizeName, field.TypeString, value)
		_node.PrizeName = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(lotterydrawrecord.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.BalanceBefore(); ok {
		_spec.SetField(lotterydrawrecord.FieldBalanceBefore, field.TypeFloat64, value)
		_node.BalanceBefore = value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(lotterydrawrecord.FieldBalanceAfter, field.TypeFloat64, value)
		_node.BalanceAfter = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(lotterydrawrecord.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.ConfigSnapshot(); ok {
		_spec.SetField(lotterydrawrecord.FieldConfigSnapshot, field.TypeJSON, value)
		_node.ConfigSnapshot = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotterydrawrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydrawrecord.UserTable,
			Columns: []string{lotterydrawrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChanceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydrawrecord.ChanceTable,
			Columns: []string{lotterydrawrecord.ChanceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterychance.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChanceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PrizeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydrawrecord.PrizeTable,
			Columns: []string{lotterydrawrecord.PrizeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PrizeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryDrawRecord.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryDrawRecordUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryDrawRecordCreate) OnConflict(opts ...sql.ConflictOption) *LotteryDrawRecordUpsertOne {
	_c.conflict = opts
	return &LotteryDrawRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryDrawRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryDrawRecordCreate) OnConflictColumns(columns ...string) *LotteryDrawRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryDrawRecordUpsertOne{
		create: _c,
	}
}

type (
	// LotteryDrawRecordUpsertOne is the builder for "upsert"-ing
	//  one LotteryDrawRecord node.
	LotteryDrawRecordUpsertOne struct {
		create *LotteryDrawRecordCreate
	}

	// LotteryDrawRecordUpsert is the "OnConflict" setter.
	LotteryDrawRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *LotteryDrawRecordUpsert) SetUserID(v int64) *LotteryDrawRecordUpsert {
	u.Set(lotterydrawrecord.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsert) UpdateUserID() *LotteryDrawRecordUpsert {
	u.SetExcluded(lotterydrawrecord.FieldUserID)
	return u
}

// SetChanceID sets the "chance_id" field.
func (u *LotteryDrawRecordUpsert) SetChanceID(v int64) *LotteryDrawRecordUpsert {
	u.Set(lotterydrawrecord.FieldChanceID, v)
	return u
}

// UpdateChanceID sets the "chance_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsert) UpdateChanceID() *LotteryDrawRecordUpsert {
	u.SetExcluded(lotterydrawrecord.FieldChanceID)
	return u
}

// SetPrizeID sets the "prize_id" field.
func (u *LotteryDrawRecordUpsert) SetPrizeID(v int64) *LotteryDrawRecordUpsert {
	u.Set(lotterydrawrecord.FieldPrizeID, v)
	return u
}

// UpdatePrizeID sets the "prize_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsert) UpdatePrizeID() *LotteryDrawRecordUpsert {
	u.SetExcluded(lotterydrawrecord.FieldPrizeID)
	return u
}

// SetPrizeName sets the "prize_name" field.
func (u *LotteryDrawRecordUpsert) SetPrizeName(v string) *LotteryDrawRecordUpsert {
	u.Set(lotterydrawrecord.FieldPrizeName, v)
	return u
}

// UpdatePrizeName sets the "prize_name" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsert) UpdatePrizeName() *LotteryDrawRecordUpsert {
	u.SetExcluded(lotterydrawrecord.FieldPrizeName)
	return u
}

// SetAmount sets the "amount" field.
func (u *LotteryDrawRecordUpsert) SetAmount(v float64) *LotteryDrawRecordUpsert {
	u.Set(lotterydrawrecord.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsert) UpdateAmount() *LotteryDrawRecordUpsert {
	u.SetExcluded(lotterydrawrecord.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *LotteryDrawRecordUpsert) AddAmount(v float64) *LotteryDrawRecordUpsert {
	u.Add(lotterydrawrecord.FieldAmount, v)
	return u
}

// SetBalanceBefore sets the "balance_before" field.
func (u *LotteryDrawRecordUpsert) SetBalanceBefore(v float64) *LotteryDrawRecordUpsert {
	u.Set(lotterydrawrecord.FieldBalanceBefore, v)
	return u
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsert) UpdateBalanceBefore() *LotteryDrawRecordUpsert {
	u.SetExcluded(lotterydrawrecord.FieldBalanceBefore)
	return u
}

// AddBalanceBefore adds v to the "balance_before" field.
func (u *LotteryDrawRecordUpsert) AddBalanceBefore(v float64) *LotteryDrawRecordUpsert {
	u.Add(lotterydrawrecord.FieldBalanceBefore, v)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *LotteryDrawRecordUpsert) SetBalanceAfter(v float64) *LotteryDrawRecordUpsert {
	u.Set(lotterydrawrecord.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsert) UpdateBalanceAfter() *LotteryDrawRecordUpsert {
	u.SetExcluded(lotterydrawrecord.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *LotteryDrawRecordUpsert) AddBalanceAfter(v float64) *LotteryDrawRecordUpsert {
	u.Add(lotterydrawrecord.FieldBalanceAfter, v)
	return u
}

// SetSourceType sets the "source_type" field.
func (u *LotteryDrawRecordUpsert) SetSourceType(v string) *LotteryDrawRecordUpsert {
	u.Set(lotterydrawrecord.FieldSourceType, v)
	return u
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsert) UpdateSourceType() *LotteryDrawRecordUpsert {
	u.SetExcluded(lotterydrawrecord.FieldSourceType)
	return u
}

// SetConfigSnapshot sets the "config_snapshot" field.
func (u *LotteryDrawRecordUpsert) SetConfigSnapshot(v map[string]interface{}) *LotteryDrawRecordUpsert {
	u.Set(lotterydrawrecord.FieldConfigSnapshot, v)
	return u
}

// UpdateConfigSnapshot sets the "config_snapshot" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsert) UpdateConfigSnapshot() *LotteryDrawRecordUpsert {
	u.SetExcluded(lotterydrawrecord.FieldConfigSnapshot)
	return u
}

// ClearConfigSnapshot clears the value of the "config_snapshot" field.
func (u *LotteryDrawRecordUpsert) ClearConfigSnapshot() *LotteryDrawRecordUpsert {
	u.SetNull(lotterydrawrecord.FieldConfigSnapshot)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryDrawRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryDrawRecordUpsertOne) UpdateNewValues() *LotteryDrawRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotterydrawrecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryDrawRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryDrawRecordUpsertOne) Ignore() *LotteryDrawRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryDrawRecordUpsertOne) DoNothing() *LotteryDrawRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryDrawRecordCreate.OnConflict
// documentation for more info.
func (u *LotteryDrawRecordUpsertOne) Update(set func(*LotteryDrawRecordUpsert)) *LotteryDrawRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryDrawRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *LotteryDrawRecordUpsertOne) SetUserID(v int64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertOne) UpdateUserID() *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetChanceID sets the "chance_id" field.
func (u *LotteryDrawRecordUpsertOne) SetChanceID(v int64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetChanceID(v)
	})
}

// UpdateChanceID sets the "chance_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertOne) UpdateChanceID() *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateChanceID()
	})
}

// SetPrizeID sets the "prize_id" field.
func (u *LotteryDrawRecordUpsertOne) SetPrizeID(v int64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetPrizeID(v)
	})
}

// UpdatePrizeID sets the "prize_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertOne) UpdatePrizeID() *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdatePrizeID()
	})
}

// SetPrizeName sets the "prize_name" field.
func (u *LotteryDrawRecordUpsertOne) SetPrizeName(v string) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetPrizeName(v)
	})
}

// UpdatePrizeName sets the "prize_name" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertOne) UpdatePrizeName() *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdatePrizeName()
	})
}

// SetAmount sets the "amount" field.
func (u *LotteryDrawRecordUpsertOne) SetAmount(v float64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *LotteryDrawRecordUpsertOne) AddAmount(v float64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertOne) UpdateAmount() *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceBefore sets the "balance_before" field.
func (u *LotteryDrawRecordUpsertOne) SetBalanceBefore(v float64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetBalanceBefore(v)
	})
}

// AddBalanceBefore adds v to the "balance_before" field.
func (u *LotteryDrawRecordUpsertOne) AddBalanceBefore(v float64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.AddBalanceBefore(v)
	})
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertOne) UpdateBalanceBefore() *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateBalanceBefore()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *LotteryDrawRecordUpsertOne) SetBalanceAfter(v float64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *LotteryDrawRecordUpsertOne) AddBalanceAfter(v float64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertOne) UpdateBalanceAfter() *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetSourceType sets the "source_type" field.
func (u *LotteryDrawRecordUpsertOne) SetSourceType(v string) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertOne) UpdateSourceType() *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateSourceType()
	})
}

// SetConfigSnapshot sets the "config_snapshot" field.
func (u *LotteryDrawRecordUpsertOne) SetConfigSnapshot(v map[string]interface{}) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetConfigSnapshot(v)
	})
}

// UpdateConfigSnapshot sets the "config_snapshot" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertOne) UpdateConfigSnapshot() *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateConfigSnapshot()
	})
}

// ClearConfigSnapshot clears the value of the "config_snapshot" field.
func (u *LotteryDrawRecordUpsertOne) ClearConfigSnapshot() *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.ClearConfigSnapshot()
	})
}

// Exec executes the query.
func (u *LotteryDrawRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryDrawRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryDrawRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryDrawRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryDrawRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryDrawRecordCreateBulk is the builder for creating many LotteryDrawRecord entities in bulk.
type LotteryDrawRecordCreateBulk struct {
	config
	err      error
	builders []*LotteryDrawRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryDrawRecord entities in the database.
func (_c *LotteryDrawRecordCreateBulk) Save(ctx context.Context) ([]*LotteryDrawRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryDrawRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryDrawRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryDrawRecordCreateBulk) SaveX(ctx context.Context) []*LotteryDrawRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryDrawRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryDrawRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryDrawRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryDrawRecordUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryDrawRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryDrawRecordUpsertBulk {
	_c.conflict = opts
	return &LotteryDrawRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryDrawRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryDrawRecordCreateBulk) OnConflictColumns(columns ...string) *LotteryDrawRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryDrawRecordUpsertBulk{
		create: _c,
	}
}

// LotteryDrawRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryDrawRecord nodes.
type LotteryDrawRecordUpsertBulk struct {
	create *LotteryDrawRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryDrawRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryDrawRecordUpsertBulk) UpdateNewValues() *LotteryDrawRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotterydrawrecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryDrawRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryDrawRecordUpsertBulk) Ignore() *LotteryDrawRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryDrawRecordUpsertBulk) DoNothing() *LotteryDrawRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryDrawRecordCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryDrawRecordUpsertBulk) Update(set func(*LotteryDrawRecordUpsert)) *LotteryDrawRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryDrawRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *LotteryDrawRecordUpsertBulk) SetUserID(v int64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertBulk) UpdateUserID() *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetChanceID sets the "chance_id" field.
func (u *LotteryDrawRecordUpsertBulk) SetChanceID(v int64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetChanceID(v)
	})
}

// UpdateChanceID sets the "chance_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertBulk) UpdateChanceID() *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateChanceID()
	})
}

// SetPrizeID sets the "prize_id" field.
func (u *LotteryDrawRecordUpsertBulk) SetPrizeID(v int64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetPrizeID(v)
	})
}

// UpdatePrizeID sets the "prize_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertBulk) UpdatePrizeID() *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdatePrizeID()
	})
}

// SetPrizeName sets the "prize_name" field.
func (u *LotteryDrawRecordUpsertBulk) SetPrizeName(v string) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetPrizeName(v)
	})
}

// UpdatePrizeName sets the "prize_name" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertBulk) UpdatePrizeName() *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdatePrizeName()
	})
}

// SetAmount sets the "amount" field.
func (u *LotteryDrawRecordUpsertBulk) SetAmount(v float64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *LotteryDrawRecordUpsertBulk) AddAmount(v float64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertBulk) UpdateAmount() *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceBefore sets the "balance_before" field.
func (u *LotteryDrawRecordUpsertBulk) SetBalanceBefore(v float64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetBalanceBefore(v)
	})
}

// AddBalanceBefore adds v to the "balance_before" field.
func (u *LotteryDrawRecordUpsertBulk) AddBalanceBefore(v float64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.AddBalanceBefore(v)
	})
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertBulk) UpdateBalanceBefore() *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateBalanceBefore()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *LotteryDrawRecordUpsertBulk) SetBalanceAfter(v float64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *LotteryDrawRecordUpsertBulk) AddBalanceAfter(v float64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertBulk) UpdateBalanceAfter() *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetSourceType sets the "source_type" field.
func (u *LotteryDrawRecordUpsertBulk) SetSourceType(v string) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertBulk) UpdateSourceType() *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateSourceType()
	})
}

// SetConfigSnapshot sets the "config_snapshot" field.
func (u *LotteryDrawRecordUpsertBulk) SetConfigSnapshot(v map[string]interface{}) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetConfigSnapshot(v)
	})
}

// UpdateConfigSnapshot sets the "config_snapshot" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertBulk) UpdateConfigSnapshot() *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateConfigSnapshot()
	})
}

// ClearConfigSnapshot clears the value of the "config_snapshot" field.
func (u *LotteryDrawRecordUpsertBulk) ClearConfigSnapshot() *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.ClearConfigSnapshot()
	})
}

// Exec executes the query.
func (u *LotteryDrawRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryDrawRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryDrawRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryDrawRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
