// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterychance"
	"github.com/Wei-Shaw/sub2api/ent/lotterydrawrecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// LotteryChanceUpdate is the builder for updating LotteryChance entities.
type LotteryChanceUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryChanceMutation
}

// Where appends a list predicates to the LotteryChanceUpdate builder.
func (_u *LotteryChanceUpdate) Where(ps ...predicate.LotteryChance) *LotteryChanceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LotteryChanceUpdate) SetUserID(v int64) *LotteryChanceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryChanceUpdate) SetNillableUserID(v *int64) *LotteryChanceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *LotteryChanceUpdate) SetSourceType(v string) *LotteryChanceUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *LotteryChanceUpdate) SetNillableSourceType(v *string) *LotteryChanceUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceKey sets the "source_key" field.
func (_u *LotteryChanceUpdate) SetSourceKey(v string) *LotteryChanceUpdate {
	_u.mutation.SetSourceKey(v)
	return _u
}

// SetNillableSourceKey sets the "source_key" field if the given value is not nil.
func (_u *LotteryChanceUpdate) SetNillableSourceKey(v *string) *LotteryChanceUpdate {
	if v != nil {
		_u.SetSourceKey(*v)
	}
	return _u
}

// SetTotalCount sets the "total_count" field.
func (_u *LotteryChanceUpdate) SetTotalCount(v int) *LotteryChanceUpdate {
	_u.mutation.ResetTotalCount()
	_u.mutation.SetTotalCount(v)
	return _u
}

// SetNillableTotalCount sets the "total_count" field if the given value is not nil.
func (_u *LotteryChanceUpdate) SetNillableTotalCount(v *int) *LotteryChanceUpdate {
	if v != nil {
		_u.SetTotalCount(*v)
	}
	return _u
}

// AddTotalCount adds value to the "total_count" field.
func (_u *LotteryChanceUpdate) AddTotalCount(v int) *LotteryChanceUpdate {
	_u.mutation.AddTotalCount(v)
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *LotteryChanceUpdate) SetUsedCount(v int) *LotteryChanceUpdate {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *LotteryChanceUpdate) SetNillableUsedCount(v *int) *LotteryChanceUpdate {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *LotteryChanceUpdate) AddUsedCount(v int) *LotteryChanceUpdate {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetSourceAmount sets the "source_amount" field.
func (_u *LotteryChanceUpdate) SetSourceAmount(v float64) *LotteryChanceUpdate {
	_u.mutation.ResetSourceAmount()
	_u.mutation.SetSourceAmount(v)
	return _u
}

// SetNillableSourceAmount sets the "source_amount" field if the given value is not nil.
func (_u *LotteryChanceUpdate) SetNillableSourceAmount(v *float64) *LotteryChanceUpdate {
	if v != nil {
		_u.SetSourceAmount(*v)
	}
	return _u
}

// AddSourceAmount adds value to the "source_amount" field.
func (_u *LotteryChanceUpdate) AddSourceAmount(v float64) *LotteryChanceUpdate {
	_u.mutation.AddSourceAmount(v)
	return _u
}

// SetGrantDate sets the "grant_date" field.
func (_u *LotteryChanceUpdate) SetGrantDate(v time.Time) *LotteryChanceUpdate {
	_u.mutation.SetGrantDate(v)
	return _u
}

// SetNillableGrantDate sets the "grant_date" field if the given value is not nil.
func (_u *LotteryChanceUpdate) SetNillableGrantDate(v *time.Time) *LotteryChanceUpdate {
	if v != nil {
		_u.SetGrantDate(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *LotteryChanceUpdate) SetExpiresAt(v time.Time) *LotteryChanceUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *LotteryChanceUpdate) SetNillableExpiresAt(v *time.Time) *LotteryChanceUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *LotteryChanceUpdate) SetNotes(v string) *LotteryChanceUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *LotteryChanceUpdate) SetNillableNotes(v *string) *LotteryChanceUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *LotteryChanceUpdate) ClearNotes() *LotteryChanceUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryChanceUpdate) SetUpdatedAt(v time.Time) *LotteryChanceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *LotteryChanceUpdate) SetUser(v *User) *LotteryChanceUpdate {
	return _u.SetUserID(v.ID)
}

// AddDrawRecordIDs adds the "draw_records" edge to the LotteryDrawRecord entity by IDs.
func (_u *LotteryChanceUpdate) AddDrawRecordIDs(ids ...int64) *LotteryChanceUpdate {
	_u.mutation.AddDrawRecordIDs(ids...)
	return _u
}

// AddDrawRecords adds the "draw_records" edges to the LotteryDrawRecord entity.
func (_u *LotteryChanceUpdate) AddDrawRecords(v ...*LotteryDrawRecord) *LotteryChanceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDrawRecordIDs(ids...)
}

// Mutation returns the LotteryChanceMutation object of the builder.
func (_u *LotteryChanceUpdate) Mutation() *LotteryChanceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *LotteryChanceUpdate) ClearUser() *LotteryChanceUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearDrawRecords clears all "draw_records" edges to the LotteryDrawRecord entity.
func (_u *LotteryChanceUpdate) ClearDrawRecords() *LotteryChanceUpdate {
	_u.mutation.ClearDrawRecords()
	return _u
}

// RemoveDrawRecordIDs removes the "draw_records" edge to LotteryDrawRecord entities by IDs.
func (_u *LotteryChanceUpdate) RemoveDrawRecordIDs(ids ...int64) *LotteryChanceUpdate {
	_u.mutation.RemoveDrawRecordIDs(ids...)
	return _u
}

// RemoveDrawRecords removes "draw_records" edges to LotteryDrawRecord entities.
func (_u *LotteryChanceUpdate) RemoveDrawRecords(v ...*LotteryDrawRecord) *LotteryChanceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDrawRecordIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryChanceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryChanceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryChanceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryChanceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryChanceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotterychance.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryChanceUpdate) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := lotterychance.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "LotteryChance.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceKey(); ok {
		if err := lotterychance.SourceKeyValidator(v); err != nil {
			return &ValidationError{Name: "source_key", err: fmt.Errorf(`ent: validator failed for field "LotteryChance.source_key": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryChance.user"`)
	}
	return nil
}

func (_u *LotteryChanceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterychance.Table, lotterychance.Columns, sqlgraph.NewFieldSpec(lotterychance.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(lotterychance.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceKey(); ok {
		_spec.SetField(lotterychance.FieldSourceKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalCount(); ok {
		_spec.SetField(lotterychance.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCount(); ok {
		_spec.AddField(lotterychance.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(lotterychance.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(lotterychance.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceAmount(); ok {
		_spec.SetField(lotterychance.FieldSourceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSourceAmount(); ok {
		_spec.AddField(lotterychance.FieldSourceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GrantDate(); ok {
		_spec.SetField(lotterychance.FieldGrantDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(lotterychance.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(lotterychance.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(lotterychance.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterychance.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterychance.UserTable,
			Columns: []string{lotterychance.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterychance.UserTable,
			Columns: []string{lotterychance.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DrawRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotterychance.DrawRecordsTable,
			Columns: []string{lotterychance.DrawRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterydrawrecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDrawRecordsIDs(); len(nodes) > 0 && !_u.mutation.DrawRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotterychance.DrawRecordsTable,
			Columns: []string{lotterychance.DrawRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterydrawrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DrawRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotterychance.DrawRecordsTable,
			Columns: []string{lotterychance.DrawRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterydrawrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterychance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryChanceUpdateOne is the builder for updating a single LotteryChance entity.
type LotteryChanceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryChanceMutation
}

// SetUserID sets the "user_id" field.
func (_u *LotteryChanceUpdateOne) SetUserID(v int64) *LotteryChanceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryChanceUpdateOne) SetNillableUserID(v *int64) *LotteryChanceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *LotteryChanceUpdateOne) SetSourceType(v string) *LotteryChanceUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *LotteryChanceUpdateOne) SetNillableSourceType(v *string) *LotteryChanceUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceKey sets the "source_key" field.
func (_u *LotteryChanceUpdateOne) SetSourceKey(v string) *LotteryChanceUpdateOne {
	_u.mutation.SetSourceKey(v)
	return _u
}

// SetNillableSourceKey sets the "source_key" field if the given value is not nil.
func (_u *LotteryChanceUpdateOne) SetNillableSourceKey(v *string) *LotteryChanceUpdateOne {
	if v != nil {
		_u.SetSourceKey(*v)
	}
	return _u
}

// SetTotalCount sets the "total_count" field.
func (_u *LotteryChanceUpdateOne) SetTotalCount(v int) *LotteryChanceUpdateOne {
	_u.mutation.ResetTotalCount()
	_u.mutation.SetTotalCount(v)
	return _u
}

// SetNillableTotalCount sets the "total_count" field if the given value is not nil.
func (_u *LotteryChanceUpdateOne) SetNillableTotalCount(v *int) *LotteryChanceUpdateOne {
	if v != nil {
		_u.SetTotalCount(*v)
	}
	return _u
}

// AddTotalCount adds value to the "total_count" field.
func (_u *LotteryChanceUpdateOne) AddTotalCount(v int) *LotteryChanceUpdateOne {
	_u.mutation.AddTotalCount(v)
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *LotteryChanceUpdateOne) SetUsedCount(v int) *LotteryChanceUpdateOne {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *LotteryChanceUpdateOne) SetNillableUsedCount(v *int) *LotteryChanceUpdateOne {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *LotteryChanceUpdateOne) AddUsedCount(v int) *LotteryChanceUpdateOne {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetSourceAmount sets the "source_amount" field.
func (_u *LotteryChanceUpdateOne) SetSourceAmount(v float64) *LotteryChanceUpdateOne {
	_u.mutation.ResetSourceAmount()
	_u.mutation.SetSourceAmount(v)
	return _u
}

// SetNillableSourceAmount sets the "source_amount" field if the given value is not nil.
func (_u *LotteryChanceUpdateOne) SetNillableSourceAmount(v *float64) *LotteryChanceUpdateOne {
	if v != nil {
		_u.SetSourceAmount(*v)
	}
	return _u
}

// AddSourceAmount adds value to the "source_amount" field.
func (_u *LotteryChanceUpdateOne) AddSourceAmount(v float64) *LotteryChanceUpdateOne {
	_u.mutation.AddSourceAmount(v)
	return _u
}

// SetGrantDate sets the "grant_date" field.
func (_u *LotteryChanceUpdateOne) SetGrantDate(v time.Time) *LotteryChanceUpdateOne {
	_u.mutation.SetGrantDate(v)
	return _u
}

// SetNillableGrantDate sets the "grant_date" field if the given value is not nil.
func (_u *LotteryChanceUpdateOne) SetNillableGrantDate(v *time.Time) *LotteryChanceUpdateOne {
	if v != nil {
		_u.SetGrantDate(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *LotteryChanceUpdateOne) SetExpiresAt(v time.Time) *LotteryChanceUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *LotteryChanceUpdateOne) SetNillableExpiresAt(v *time.Time) *LotteryChanceUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *LotteryChanceUpdateOne) SetNotes(v string) *LotteryChanceUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *LotteryChanceUpdateOne) SetNillableNotes(v *string) *LotteryChanceUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *LotteryChanceUpdateOne) ClearNotes() *LotteryChanceUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryChanceUpdateOne) SetUpdatedAt(v time.Time) *LotteryChanceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *LotteryChanceUpdateOne) SetUser(v *User) *LotteryChanceUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddDrawRecordIDs adds the "draw_records" edge to the LotteryDrawRecord entity by IDs.
func (_u *LotteryChanceUpdateOne) AddDrawRecordIDs(ids ...int64) *LotteryChanceUpdateOne {
	_u.mutation.AddDrawRecordIDs(ids...)
	return _u
}

// AddDrawRecords adds the "draw_records" edges to the LotteryDrawRecord entity.
func (_u *LotteryChanceUpdateOne) AddDrawRecords(v ...*LotteryDrawRecord) *LotteryChanceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDrawRecordIDs(ids...)
}

// Mutation returns the LotteryChanceMutation object of the builder.
func (_u *LotteryChanceUpdateOne) Mutation() *LotteryChanceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *LotteryChanceUpdateOne) ClearUser() *LotteryChanceUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearDrawRecords clears all "draw_records" edges to the LotteryDrawRecord entity.
func (_u *LotteryChanceUpdateOne) ClearDrawRecords() *LotteryChanceUpdateOne {
	_u.mutation.ClearDrawRecords()
	return _u
}

// RemoveDrawRecordIDs removes the "draw_records" edge to LotteryDrawRecord entities by IDs.
func (_u *LotteryChanceUpdateOne) RemoveDrawRecordIDs(ids ...int64) *LotteryChanceUpdateOne {
	_u.mutation.RemoveDrawRecordIDs(ids...)
	return _u
}

// RemoveDrawRecords removes "draw_records" edges to LotteryDrawRecord entities.
func (_u *LotteryChanceUpdateOne) RemoveDrawRecords(v ...*LotteryDrawRecord) *LotteryChanceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDrawRecordIDs(ids...)
}

// Where appends a list predicates to the LotteryChanceUpdate builder.
func (_u *LotteryChanceUpdateOne) Where(ps ...predicate.LotteryChance) *LotteryChanceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryChanceUpdateOne) Select(field string, fields ...string) *LotteryChanceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryChance entity.
func (_u *LotteryChanceUpdateOne) Save(ctx context.Context) (*LotteryChance, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryChanceUpdateOne) SaveX(ctx context.Context) *LotteryChance {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryChanceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryChanceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryChanceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotterychance.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryChanceUpdateOne) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := lotterychance.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "LotteryChance.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceKey(); ok {
		if err := lotterychance.SourceKeyValidator(v); err != nil {
			return &ValidationError{Name: "source_key", err: fmt.Errorf(`ent: validator failed for field "LotteryChance.source_key": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryChance.user"`)
	}
	return nil
}

func (_u *LotteryChanceUpdateOne) sqlSave(ctx context.Context) (_node *LotteryChance, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterychance.Table, lotterychance.Columns, sqlgraph.NewFieldSpec(lotterychance.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryChance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotterychance.FieldID)
		for _, f := range fields {
			if !lotterychance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotterychance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(lotterychance.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceKey(); ok {
		_spec.SetField(lotterychance.FieldSourceKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalCount(); ok {
		_spec.SetField(lotterychance.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCount(); ok {
		_spec.AddField(lotterychance.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(lotterychance.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(lotterychance.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceAmount(); ok {
		_spec.SetField(lotterychance.FieldSourceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSourceAmount(); ok {
		_spec.AddField(lotterychance.FieldSourceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GrantDate(); ok {
		_spec.SetField(lotterychance.FieldGrantDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(lotterychance.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(lotterychance.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(lotterychance.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterychance.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterychance.UserTable,
			Columns: []string{lotterychance.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterychance.UserTable,
			Columns: []string{lotterychance.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DrawRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotterychance.DrawRecordsTable,
			Columns: []string{lotterychance.DrawRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterydrawrecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDrawRecordsIDs(); len(nodes) > 0 && !_u.mutation.DrawRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotterychance.DrawRecordsTable,
			Columns: []string{lotterychance.DrawRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterydrawrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DrawRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotterychance.DrawRecordsTable,
			Columns: []string{lotterychance.DrawRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterydrawrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LotteryChance{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterychance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
