// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterychance"
	"github.com/Wei-Shaw/sub2api/ent/lotterydrawrecord"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprize"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// LotteryDrawRecordUpdate is the builder for updating LotteryDrawRecord entities.
type LotteryDrawRecordUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryDrawRecordMutation
}

// Where appends a list predicates to the LotteryDrawRecordUpdate builder.
func (_u *LotteryDrawRecordUpdate) Where(ps ...predicate.LotteryDrawRecord) *LotteryDrawRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LotteryDrawRecordUpdate) SetUserID(v int64) *LotteryDrawRecordUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdate) SetNillableUserID(v *int64) *LotteryDrawRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetChanceID sets the "chance_id" field.
func (_u *LotteryDrawRecordUpdate) SetChanceID(v int64) *LotteryDrawRecordUpdate {
	_u.mutation.SetChanceID(v)
	return _u
}

// SetNillableChanceID sets the "chance_id" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdate) SetNillableChanceID(v *int64) *LotteryDrawRecordUpdate {
	if v != nil {
		_u.SetChanceID(*v)
	}
	return _u
}

// SetPrizeID sets the "prize_id" field.
func (_u *LotteryDrawRecordUpdate) SetPrizeID(v int64) *LotteryDrawRecordUpdate {
	_u.mutation.SetPrizeID(v)
	return _u
}

// SetNillablePrizeID sets the "prize_id" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdate) SetNillablePrizeID(v *int64) *LotteryDrawRecordUpdate {
	if v != nil {
		_u.SetPrizeID(*v)
	}
	return _u
}

// SetPrizeName sets the "prize_name" field.
func (_u *LotteryDrawRecordUpdate) SetPrizeName(v string) *LotteryDrawRecordUpdate {
	_u.mutation.SetPrizeName(v)
	return _u
}

// SetNillablePrizeName sets the "prize_name" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdate) SetNillablePrizeName(v *string) *LotteryDrawRecordUpdate {
	if v != nil {
		_u.SetPrizeName(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *LotteryDrawRecordUpdate) SetAmount(v float64) *LotteryDrawRecordUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdate) SetNillableAmount(v *float64) *LotteryDrawRecordUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *LotteryDrawRecordUpdate) AddAmount(v float64) *LotteryDrawRecordUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *LotteryDrawRecordUpdate) SetBalanceBefore(v float64) *LotteryDrawRecordUpdate {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdate) SetNillableBalanceBefore(v *float64) *LotteryDrawRecordUpdate {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *LotteryDrawRecordUpdate) AddBalanceBefore(v float64) *LotteryDrawRecordUpdate {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *LotteryDrawRecordUpdate) SetBalanceAfter(v float64) *LotteryDrawRecordUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdate) SetNillableBalanceAfter(v *float64) *LotteryDrawRecordUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *LotteryDrawRecordUpdate) AddBalanceAfter(v float64) *LotteryDrawRecordUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *LotteryDrawRecordUpdate) SetSourceType(v string) *LotteryDrawRecordUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdate) SetNillableSourceType(v *string) *LotteryDrawRecordUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetConfigSnapshot sets the "config_snapshot" field.
func (_u *LotteryDrawRecordUpdate) SetConfigSnapshot(v map[string]interface{}) *LotteryDrawRecordUpdate {
	_u.mutation.SetConfigSnapshot(v)
	return _u
}

// ClearConfigSnapshot clears the value of the "config_snapshot" field.
func (_u *LotteryDrawRecordUpdate) ClearConfigSnapshot() *LotteryDrawRecordUpdate {
	_u.mutation.ClearConfigSnapshot()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *LotteryDrawRecordUpdate) SetUser(v *User) *LotteryDrawRecordUpdate {
	return _u.SetUserID(v.ID)
}

// SetChance sets the "chance" edge to the LotteryChance entity.
func (_u *LotteryDrawRecordUpdate) SetChance(v *LotteryChance) *LotteryDrawRecordUpdate {
	return _u.SetChanceID(v.ID)
}

// SetPrize sets the "prize" edge to the LotteryPrize entity.
func (_u *LotteryDrawRecordUpdate) SetPrize(v *LotteryPrize) *LotteryDrawRecordUpdate {
	return _u.SetPrizeID(v.ID)
}

// Mutation returns the LotteryDrawRecordMutation object of the builder.
func (_u *LotteryDrawRecordUpdate) Mutation() *LotteryDrawRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *LotteryDrawRecordUpdate) ClearUser() *LotteryDrawRecordUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearChance clears the "chance" edge to the LotteryChance entity.
func (_u *LotteryDrawRecordUpdate) ClearChance() *LotteryDrawRecordUpdate {
	_u.mutation.ClearChance()
	return _u
}

// ClearPrize clears the "prize" edge to the LotteryPrize entity.
func (_u *LotteryDrawRecordUpdate) ClearPrize() *LotteryDrawRecordUpdate {
	_u.mutation.ClearPrize()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryDrawRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryDrawRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryDrawRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryDrawRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryDrawRecordUpdate) check() error {
	if v, ok := _u.mutation.PrizeName(); ok {
		if err := lotterydrawrecord.PrizeNameValidator(v); err != nil {
			return &ValidationError{Name: "prize_name", err: fmt.Errorf(`ent: validator failed for field "LotteryDrawRecord.prize_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := lotterydrawrecord.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "LotteryDrawRecord.source_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryDrawRecord.user"`)
	}
	if _u.mutation.ChanceCleared() && len(_u.mutation.ChanceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryDrawRecord.chance"`)
	}
	if _u.mutation.PrizeCleared() && len(_u.mutation.PrizeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryDrawRecord.prize"`)
	}
	return nil
}

func (_u *LotteryDrawRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterydrawrecord.Table, lotterydrawrecord.Columns, sqlgraph.NewFieldSpec(lotterydrawrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PrizeName(); ok {
		_spec.SetField(lotterydrawrecord.FieldPrizeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(lotterydrawrecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(lotterydrawrecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(lotterydrawrecord.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(lotterydrawrecord.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(lotterydrawrecord.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(lotterydrawrecord.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(lotterydrawrecord.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfigSnapshot(); ok {
		_spec.SetField(lotterydrawrecord.FieldConfigSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.ConfigSnapshotCleared() {
		_spec.ClearField(lotterydrawrecord.FieldConfigSnapshot, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydrawrecord.UserTable,
			Columns: []string{lotterydrawrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydrawrecord.UserTable,
			Columns: []string{lotterydrawrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChanceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydrawrecord.ChanceTable,
			Columns: []string{lotterydrawrecord.ChanceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterychance.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChanceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydrawrecord.ChanceTable,
			Columns: []string{lotterydrawrecord.ChanceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterychance.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrizeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydrawrecord.PrizeTable,
			Columns: []string{lotterydrawrecord.PrizeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrizeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydrawrecord.PrizeTable,
			Columns: []string{lotterydrawrecord.PrizeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterydrawrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryDrawRecordUpdateOne is the builder for updating a single LotteryDrawRecord entity.
type LotteryDrawRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryDrawRecordMutation
}

// SetUserID sets the "user_id" field.
func (_u *LotteryDrawRecordUpdateOne) SetUserID(v int64) *LotteryDrawRecordUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdateOne) SetNillableUserID(v *int64) *LotteryDrawRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetChanceID sets the "chance_id" field.
func (_u *LotteryDrawRecordUpdateOne) SetChanceID(v int64) *LotteryDrawRecordUpdateOne {
	_u.mutation.SetChanceID(v)
	return _u
}

// SetNillableChanceID sets the "chance_id" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdateOne) SetNillableChanceID(v *int64) *LotteryDrawRecordUpdateOne {
	if v != nil {
		_u.SetChanceID(*v)
	}
	return _u
}

// SetPrizeID sets the "prize_id" field.
func (_u *LotteryDrawRecordUpdateOne) SetPrizeID(v int64) *LotteryDrawRecordUpdateOne {
	_u.mutation.SetPrizeID(v)
	return _u
}

// SetNillablePrizeID sets the "prize_id" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdateOne) SetNillablePrizeID(v *int64) *LotteryDrawRecordUpdateOne {
	if v != nil {
		_u.SetPrizeID(*v)
	}
	return _u
}

// SetPrizeName sets the "prize_name" field.
func (_u *LotteryDrawRecordUpdateOne) SetPrizeName(v string) *LotteryDrawRecordUpdateOne {
	_u.mutation.SetPrizeName(v)
	return _u
}

// SetNillablePrizeName sets the "prize_name" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdateOne) SetNillablePrizeName(v *string) *LotteryDrawRecordUpdateOne {
	if v != nil {
		_u.SetPrizeName(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *LotteryDrawRecordUpdateOne) SetAmount(v float64) *LotteryDrawRecordUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdateOne) SetNillableAmount(v *float64) *LotteryDrawRecordUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *LotteryDrawRecordUpdateOne) AddAmount(v float64) *LotteryDrawRecordUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *LotteryDrawRecordUpdateOne) SetBalanceBefore(v float64) *LotteryDrawRecordUpdateOne {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdateOne) SetNillableBalanceBefore(v *float64) *LotteryDrawRecordUpdateOne {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *LotteryDrawRecordUpdateOne) AddBalanceBefore(v float64) *LotteryDrawRecordUpdateOne {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *LotteryDrawRecordUpdateOne) SetBalanceAfter(v float64) *LotteryDrawRecordUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdateOne) SetNillableBalanceAfter(v *float64) *LotteryDrawRecordUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *LotteryDrawRecordUpdateOne) AddBalanceAfter(v float64) *LotteryDrawRecordUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *LotteryDrawRecordUpdateOne) SetSourceType(v string) *LotteryDrawRecordUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdateOne) SetNillableSourceType(v *string) *LotteryDrawRecordUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetConfigSnapshot sets the "config_snapshot" field.
func (_u *LotteryDrawRecordUpdateOne) SetConfigSnapshot(v map[string]interface{}) *LotteryDrawRecordUpdateOne {
	_u.mutation.SetConfigSnapshot(v)
	return _u
}

// ClearConfigSnapshot clears the value of the "config_snapshot" field.
func (_u *LotteryDrawRecordUpdateOne) ClearConfigSnapshot() *LotteryDrawRecordUpdateOne {
	_u.mutation.ClearConfigSnapshot()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *LotteryDrawRecordUpdateOne) SetUser(v *User) *LotteryDrawRecordUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetChance sets the "chance" edge to the LotteryChance entity.
func (_u *LotteryDrawRecordUpdateOne) SetChance(v *LotteryChance) *LotteryDrawRecordUpdateOne {
	return _u.SetChanceID(v.ID)
}

// SetPrize sets the "prize" edge to the LotteryPrize entity.
func (_u *LotteryDrawRecordUpdateOne) SetPrize(v *LotteryPrize) *LotteryDrawRecordUpdateOne {
	return _u.SetPrizeID(v.ID)
}

// Mutation returns the LotteryDrawRecordMutation object of the builder.
func (_u *LotteryDrawRecordUpdateOne) Mutation() *LotteryDrawRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *LotteryDrawRecordUpdateOne) ClearUser() *LotteryDrawRecordUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearChance clears the "chance" edge to the LotteryChance entity.
func (_u *LotteryDrawRecordUpdateOne) ClearChance() *LotteryDrawRecordUpdateOne {
	_u.mutation.ClearChance()
	return _u
}

// ClearPrize clears the "prize" edge to the LotteryPrize entity.
func (_u *LotteryDrawRecordUpdateOne) ClearPrize() *LotteryDrawRecordUpdateOne {
	_u.mutation.ClearPrize()
	return _u
}

// Where appends a list predicates to the LotteryDrawRecordUpdate builder.
func (_u *LotteryDrawRecordUpdateOne) Where(ps ...predicate.LotteryDrawRecord) *LotteryDrawRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryDrawRecordUpdateOne) Select(field string, fields ...string) *LotteryDrawRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryDrawRecord entity.
func (_u *LotteryDrawRecordUpdateOne) Save(ctx context.Context) (*LotteryDrawRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryDrawRecordUpdateOne) SaveX(ctx context.Context) *LotteryDrawRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryDrawRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryDrawRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryDrawRecordUpdateOne) check() error {
	if v, ok := _u.mutation.PrizeName(); ok {
		if err := lotterydrawrecord.PrizeNameValidator(v); err != nil {
			return &ValidationError{Name: "prize_name", err: fmt.Errorf(`ent: validator failed for field "LotteryDrawRecord.prize_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := lotterydrawrecord.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "LotteryDrawRecord.source_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryDrawRecord.user"`)
	}
	if _u.mutation.ChanceCleared() && len(_u.mutation.ChanceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryDrawRecord.chance"`)
	}
	if _u.mutation.PrizeCleared() && len(_u.mutation.PrizeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryDrawRecord.prize"`)
	}
	return nil
}

func (_u *LotteryDrawRecordUpdateOne) sqlSave(ctx context.Context) (_node *LotteryDrawRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterydrawrecord.Table, lotterydrawrecord.Columns, sqlgraph.NewFieldSpec(lotterydrawrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryDrawRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotterydrawrecord.FieldID)
		for _, f := range fields {
			if !lotterydrawrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotterydrawrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PrizeName(); ok {
		_spec.SetField(lotterydrawrecord.FieldPrizeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(lotterydrawrecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(lotterydrawrecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(lotterydrawrecord.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(lotterydrawrecord.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(lotterydrawrecord.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(lotterydrawrecord.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(lotterydrawrecord.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfigSnapshot(); ok {
		_spec.SetField(lotterydrawrecord.FieldConfigSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.ConfigSnapshotCleared() {
		_spec.ClearField(lotterydrawrecord.FieldConfigSnapshot, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydrawrecord.UserTable,
			Columns: []string{lotterydrawrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydrawrecord.UserTable,
			Columns: []string{lotterydrawrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChanceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydrawrecord.ChanceTable,
			Columns: []string{lotterydrawrecord.ChanceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterychance.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChanceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydrawrecord.ChanceTable,
			Columns: []string{lotterydrawrecord.ChanceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterychance.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrizeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydrawrecord.PrizeTable,
			Columns: []string{lotterydrawrecord.PrizeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrizeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterydrawrecord.PrizeTable,
			Columns: []string{lotterydrawrecord.PrizeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LotteryDrawRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterydrawrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
