// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/lotterychance"
	"github.com/Wei-Shaw/sub2api/ent/lotterydrawrecord"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprize"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// LotteryDrawRecord is the model entity for the LotteryDrawRecord schema.
type LotteryDrawRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ChanceID holds the value of the "chance_id" field.
	ChanceID int64 `json:"chance_id,omitempty"`
	// PrizeID holds the value of the "prize_id" field.
	PrizeID int64 `json:"prize_id,omitempty"`
	// PrizeName holds the value of the "prize_name" field.
	PrizeName string `json:"prize_name,omitempty"`
	// PrizeDescription holds the value of the "prize_description" field.
	PrizeDescription string `json:"prize_description,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// BalanceBefore holds the value of the "balance_before" field.
	BalanceBefore float64 `json:"balance_before,omitempty"`
	// BalanceAfter holds the value of the "balance_after" field.
	BalanceAfter float64 `json:"balance_after,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty"`
	// ConfigSnapshot holds the value of the "config_snapshot" field.
	ConfigSnapshot map[string]interface{} `json:"config_snapshot,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LotteryDrawRecordQuery when eager-loading is set.
	Edges        LotteryDrawRecordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LotteryDrawRecordEdges holds the relations/edges for other nodes in the graph.
type LotteryDrawRecordEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Chance holds the value of the chance edge.
	Chance *LotteryChance `json:"chance,omitempty"`
	// Prize holds the value of the prize edge.
	Prize *LotteryPrize `json:"prize,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LotteryDrawRecordEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ChanceOrErr returns the Chance value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LotteryDrawRecordEdges) ChanceOrErr() (*LotteryChance, error) {
	if e.Chance != nil {
		return e.Chance, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: lotterychance.Label}
	}
	return nil, &NotLoadedError{edge: "chance"}
}

// PrizeOrErr returns the Prize value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LotteryDrawRecordEdges) PrizeOrErr() (*LotteryPrize, error) {
	if e.Prize != nil {
		return e.Prize, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: lotteryprize.Label}
	}
	return nil, &NotLoadedError{edge: "prize"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LotteryDrawRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lotterydrawrecord.FieldConfigSnapshot:
			values[i] = new([]byte)
		case lotterydrawrecord.FieldAmount, lotterydrawrecord.FieldBalanceBefore, lotterydrawrecord.FieldBalanceAfter:
			values[i] = new(sql.NullFloat64)
		case lotterydrawrecord.FieldID, lotterydrawrecord.FieldUserID, lotterydrawrecord.FieldChanceID, lotterydrawrecord.FieldPrizeID:
			values[i] = new(sql.NullInt64)
		case lotterydrawrecord.FieldPrizeName, lotterydrawrecord.FieldPrizeDescription, lotterydrawrecord.FieldSourceType:
			values[i] = new(sql.NullString)
		case lotterydrawrecord.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LotteryDrawRecord fields.
func (_m *LotteryDrawRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lotterydrawrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case lotterydrawrecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case lotterydrawrecord.FieldChanceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chance_id", values[i])
			} else if value.Valid {
				_m.ChanceID = value.Int64
			}
		case lotterydrawrecord.FieldPrizeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prize_id", values[i])
			} else if value.Valid {
				_m.PrizeID = value.Int64
			}
		case lotterydrawrecord.FieldPrizeName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prize_name", values[i])
			} else if value.Valid {
				_m.PrizeName = value.String
			}
		case lotterydrawrecord.FieldPrizeDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prize_description", values[i])
			} else if value.Valid {
				_m.PrizeDescription = value.String
			}
		case lotterydrawrecord.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case lotterydrawrecord.FieldBalanceBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_before", values[i])
			} else if value.Valid {
				_m.BalanceBefore = value.Float64
			}
		case lotterydrawrecord.FieldBalanceAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value.Valid {
				_m.BalanceAfter = value.Float64
			}
		case lotterydrawrecord.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case lotterydrawrecord.FieldConfigSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ConfigSnapshot); err != nil {
					return fmt.Errorf("unmarshal field config_snapshot: %w", err)
				}
			}
		case lotterydrawrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LotteryDrawRecord.
// This includes values selected through modifiers, order, etc.
func (_m *LotteryDrawRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the LotteryDrawRecord entity.
func (_m *LotteryDrawRecord) QueryUser() *UserQuery {
	return NewLotteryDrawRecordClient(_m.config).QueryUser(_m)
}

// QueryChance queries the "chance" edge of the LotteryDrawRecord entity.
func (_m *LotteryDrawRecord) QueryChance() *LotteryChanceQuery {
	return NewLotteryDrawRecordClient(_m.config).QueryChance(_m)
}

// QueryPrize queries the "prize" edge of the LotteryDrawRecord entity.
func (_m *LotteryDrawRecord) QueryPrize() *LotteryPrizeQuery {
	return NewLotteryDrawRecordClient(_m.config).QueryPrize(_m)
}

// Update returns a builder for updating this LotteryDrawRecord.
// Note that you need to call LotteryDrawRecord.Unwrap() before calling this method if this LotteryDrawRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LotteryDrawRecord) Update() *LotteryDrawRecordUpdateOne {
	return NewLotteryDrawRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LotteryDrawRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LotteryDrawRecord) Unwrap() *LotteryDrawRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LotteryDrawRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LotteryDrawRecord) String() string {
	var builder strings.Builder
	builder.WriteString("LotteryDrawRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("chance_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChanceID))
	builder.WriteString(", ")
	builder.WriteString("prize_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrizeID))
	builder.WriteString(", ")
	builder.WriteString("prize_name=")
	builder.WriteString(_m.PrizeName)
	builder.WriteString(", ")
	builder.WriteString("prize_description=")
	builder.WriteString(_m.PrizeDescription)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("balance_before=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceBefore))
	builder.WriteString(", ")
	builder.WriteString("balance_after=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceAfter))
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	builder.WriteString("config_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfigSnapshot))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LotteryDrawRecords is a parsable slice of LotteryDrawRecord.
type LotteryDrawRecords []*LotteryDrawRecord
