// Code generated by ent, DO NOT EDIT.

package lotteryprize

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the lotteryprize type in the database.
	Label = "lottery_prize"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldProbability holds the string denoting the probability field in the database.
	FieldProbability = "probability"
	// FieldDailyStock holds the string denoting the daily_stock field in the database.
	FieldDailyStock = "daily_stock"
	// FieldDailyUsed holds the string denoting the daily_used field in the database.
	FieldDailyUsed = "daily_used"
	// FieldTotalStock holds the string denoting the total_stock field in the database.
	FieldTotalStock = "total_stock"
	// FieldTotalUsed holds the string denoting the total_used field in the database.
	FieldTotalUsed = "total_used"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldColor holds the string denoting the color field in the database.
	FieldColor = "color"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeDrawRecords holds the string denoting the draw_records edge name in mutations.
	EdgeDrawRecords = "draw_records"
	// Table holds the table name of the lotteryprize in the database.
	Table = "lottery_prizes"
	// DrawRecordsTable is the table that holds the draw_records relation/edge.
	DrawRecordsTable = "lottery_draw_records"
	// DrawRecordsInverseTable is the table name for the LotteryDrawRecord entity.
	// It exists in this package in order to avoid circular dependency with the "lotterydrawrecord" package.
	DrawRecordsInverseTable = "lottery_draw_records"
	// DrawRecordsColumn is the table column denoting the draw_records relation/edge.
	DrawRecordsColumn = "prize_id"
)

// Columns holds all SQL columns for lotteryprize fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldAmount,
	FieldProbability,
	FieldDailyStock,
	FieldDailyUsed,
	FieldTotalStock,
	FieldTotalUsed,
	FieldEnabled,
	FieldColor,
	FieldSortOrder,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultProbability holds the default value on creation for the "probability" field.
	DefaultProbability float64
	// DefaultDailyStock holds the default value on creation for the "daily_stock" field.
	DefaultDailyStock int
	// DefaultDailyUsed holds the default value on creation for the "daily_used" field.
	DefaultDailyUsed int
	// DefaultTotalStock holds the default value on creation for the "total_stock" field.
	DefaultTotalStock int
	// DefaultTotalUsed holds the default value on creation for the "total_used" field.
	DefaultTotalUsed int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultColor holds the default value on creation for the "color" field.
	DefaultColor string
	// ColorValidator is a validator for the "color" field. It is called by the builders before save.
	ColorValidator func(string) error
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the LotteryPrize queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByProbability orders the results by the probability field.
func ByProbability(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbability, opts...).ToFunc()
}

// ByDailyStock orders the results by the daily_stock field.
func ByDailyStock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyStock, opts...).ToFunc()
}

// ByDailyUsed orders the results by the daily_used field.
func ByDailyUsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyUsed, opts...).ToFunc()
}

// ByTotalStock orders the results by the total_stock field.
func ByTotalStock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalStock, opts...).ToFunc()
}

// ByTotalUsed orders the results by the total_used field.
func ByTotalUsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalUsed, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByColor orders the results by the color field.
func ByColor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldColor, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDrawRecordsCount orders the results by draw_records count.
func ByDrawRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDrawRecordsStep(), opts...)
	}
}

// ByDrawRecords orders the results by draw_records terms.
func ByDrawRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDrawRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDrawRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DrawRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DrawRecordsTable, DrawRecordsColumn),
	)
}
