// Code generated by ent, DO NOT EDIT.

package lotteryprize

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldName, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldAmount, v))
}

// Probability applies equality check predicate on the "probability" field. It's identical to ProbabilityEQ.
func Probability(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldProbability, v))
}

// DailyStock applies equality check predicate on the "daily_stock" field. It's identical to DailyStockEQ.
func DailyStock(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldDailyStock, v))
}

// DailyUsed applies equality check predicate on the "daily_used" field. It's identical to DailyUsedEQ.
func DailyUsed(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldDailyUsed, v))
}

// TotalStock applies equality check predicate on the "total_stock" field. It's identical to TotalStockEQ.
func TotalStock(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldTotalStock, v))
}

// TotalUsed applies equality check predicate on the "total_used" field. It's identical to TotalUsedEQ.
func TotalUsed(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldTotalUsed, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldEnabled, v))
}

// Color applies equality check predicate on the "color" field. It's identical to ColorEQ.
func Color(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldColor, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldContainsFold(FieldName, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldAmount, v))
}

// ProbabilityEQ applies the EQ predicate on the "probability" field.
func ProbabilityEQ(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldProbability, v))
}

// ProbabilityNEQ applies the NEQ predicate on the "probability" field.
func ProbabilityNEQ(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldProbability, v))
}

// ProbabilityIn applies the In predicate on the "probability" field.
func ProbabilityIn(vs ...float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldProbability, vs...))
}

// ProbabilityNotIn applies the NotIn predicate on the "probability" field.
func ProbabilityNotIn(vs ...float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldProbability, vs...))
}

// ProbabilityGT applies the GT predicate on the "probability" field.
func ProbabilityGT(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldProbability, v))
}

// ProbabilityGTE applies the GTE predicate on the "probability" field.
func ProbabilityGTE(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldProbability, v))
}

// ProbabilityLT applies the LT predicate on the "probability" field.
func ProbabilityLT(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldProbability, v))
}

// ProbabilityLTE applies the LTE predicate on the "probability" field.
func ProbabilityLTE(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldProbability, v))
}

// DailyStockEQ applies the EQ predicate on the "daily_stock" field.
func DailyStockEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldDailyStock, v))
}

// DailyStockNEQ applies the NEQ predicate on the "daily_stock" field.
func DailyStockNEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldDailyStock, v))
}

// DailyStockIn applies the In predicate on the "daily_stock" field.
func DailyStockIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldDailyStock, vs...))
}

// DailyStockNotIn applies the NotIn predicate on the "daily_stock" field.
func DailyStockNotIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldDailyStock, vs...))
}

// DailyStockGT applies the GT predicate on the "daily_stock" field.
func DailyStockGT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldDailyStock, v))
}

// DailyStockGTE applies the GTE predicate on the "daily_stock" field.
func DailyStockGTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldDailyStock, v))
}

// DailyStockLT applies the LT predicate on the "daily_stock" field.
func DailyStockLT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldDailyStock, v))
}

// DailyStockLTE applies the LTE predicate on the "daily_stock" field.
func DailyStockLTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldDailyStock, v))
}

// DailyUsedEQ applies the EQ predicate on the "daily_used" field.
func DailyUsedEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldDailyUsed, v))
}

// DailyUsedNEQ applies the NEQ predicate on the "daily_used" field.
func DailyUsedNEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldDailyUsed, v))
}

// DailyUsedIn applies the In predicate on the "daily_used" field.
func DailyUsedIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldDailyUsed, vs...))
}

// DailyUsedNotIn applies the NotIn predicate on the "daily_used" field.
func DailyUsedNotIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldDailyUsed, vs...))
}

// DailyUsedGT applies the GT predicate on the "daily_used" field.
func DailyUsedGT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldDailyUsed, v))
}

// DailyUsedGTE applies the GTE predicate on the "daily_used" field.
func DailyUsedGTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldDailyUsed, v))
}

// DailyUsedLT applies the LT predicate on the "daily_used" field.
func DailyUsedLT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldDailyUsed, v))
}

// DailyUsedLTE applies the LTE predicate on the "daily_used" field.
func DailyUsedLTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldDailyUsed, v))
}

// TotalStockEQ applies the EQ predicate on the "total_stock" field.
func TotalStockEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldTotalStock, v))
}

// TotalStockNEQ applies the NEQ predicate on the "total_stock" field.
func TotalStockNEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldTotalStock, v))
}

// TotalStockIn applies the In predicate on the "total_stock" field.
func TotalStockIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldTotalStock, vs...))
}

// TotalStockNotIn applies the NotIn predicate on the "total_stock" field.
func TotalStockNotIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldTotalStock, vs...))
}

// TotalStockGT applies the GT predicate on the "total_stock" field.
func TotalStockGT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldTotalStock, v))
}

// TotalStockGTE applies the GTE predicate on the "total_stock" field.
func TotalStockGTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldTotalStock, v))
}

// TotalStockLT applies the LT predicate on the "total_stock" field.
func TotalStockLT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldTotalStock, v))
}

// TotalStockLTE applies the LTE predicate on the "total_stock" field.
func TotalStockLTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldTotalStock, v))
}

// TotalUsedEQ applies the EQ predicate on the "total_used" field.
func TotalUsedEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldTotalUsed, v))
}

// TotalUsedNEQ applies the NEQ predicate on the "total_used" field.
func TotalUsedNEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldTotalUsed, v))
}

// TotalUsedIn applies the In predicate on the "total_used" field.
func TotalUsedIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldTotalUsed, vs...))
}

// TotalUsedNotIn applies the NotIn predicate on the "total_used" field.
func TotalUsedNotIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldTotalUsed, vs...))
}

// TotalUsedGT applies the GT predicate on the "total_used" field.
func TotalUsedGT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldTotalUsed, v))
}

// TotalUsedGTE applies the GTE predicate on the "total_used" field.
func TotalUsedGTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldTotalUsed, v))
}

// TotalUsedLT applies the LT predicate on the "total_used" field.
func TotalUsedLT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldTotalUsed, v))
}

// TotalUsedLTE applies the LTE predicate on the "total_used" field.
func TotalUsedLTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldTotalUsed, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldEnabled, v))
}

// ColorEQ applies the EQ predicate on the "color" field.
func ColorEQ(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldColor, v))
}

// ColorNEQ applies the NEQ predicate on the "color" field.
func ColorNEQ(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldColor, v))
}

// ColorIn applies the In predicate on the "color" field.
func ColorIn(vs ...string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldColor, vs...))
}

// ColorNotIn applies the NotIn predicate on the "color" field.
func ColorNotIn(vs ...string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldColor, vs...))
}

// ColorGT applies the GT predicate on the "color" field.
func ColorGT(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldColor, v))
}

// ColorGTE applies the GTE predicate on the "color" field.
func ColorGTE(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldColor, v))
}

// ColorLT applies the LT predicate on the "color" field.
func ColorLT(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldColor, v))
}

// ColorLTE applies the LTE predicate on the "color" field.
func ColorLTE(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldColor, v))
}

// ColorContains applies the Contains predicate on the "color" field.
func ColorContains(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldContains(FieldColor, v))
}

// ColorHasPrefix applies the HasPrefix predicate on the "color" field.
func ColorHasPrefix(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldHasPrefix(FieldColor, v))
}

// ColorHasSuffix applies the HasSuffix predicate on the "color" field.
func ColorHasSuffix(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldHasSuffix(FieldColor, v))
}

// ColorEqualFold applies the EqualFold predicate on the "color" field.
func ColorEqualFold(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEqualFold(FieldColor, v))
}

// ColorContainsFold applies the ContainsFold predicate on the "color" field.
func ColorContainsFold(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldContainsFold(FieldColor, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasDrawRecords applies the HasEdge predicate on the "draw_records" edge.
func HasDrawRecords() predicate.LotteryPrize {
	return predicate.LotteryPrize(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DrawRecordsTable, DrawRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDrawRecordsWith applies the HasEdge predicate on the "draw_records" edge with a given conditions (other predicates).
func HasDrawRecordsWith(preds ...predicate.LotteryDrawRecord) predicate.LotteryPrize {
	return predicate.LotteryPrize(func(s *sql.Selector) {
		step := newDrawRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LotteryPrize) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LotteryPrize) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LotteryPrize) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.NotPredicates(p))
}
