// Code generated by ent, DO NOT EDIT.

package carpoolnoticeversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldTitle, v))
}

// ContentMd applies equality check predicate on the "content_md" field. It's identical to ContentMdEQ.
func ContentMd(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldContentMd, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldVersion, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldActive, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldPublishedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldContainsFold(FieldTitle, v))
}

// ContentMdEQ applies the EQ predicate on the "content_md" field.
func ContentMdEQ(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldContentMd, v))
}

// ContentMdNEQ applies the NEQ predicate on the "content_md" field.
func ContentMdNEQ(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNEQ(FieldContentMd, v))
}

// ContentMdIn applies the In predicate on the "content_md" field.
func ContentMdIn(vs ...string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldIn(FieldContentMd, vs...))
}

// ContentMdNotIn applies the NotIn predicate on the "content_md" field.
func ContentMdNotIn(vs ...string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNotIn(FieldContentMd, vs...))
}

// ContentMdGT applies the GT predicate on the "content_md" field.
func ContentMdGT(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldGT(FieldContentMd, v))
}

// ContentMdGTE applies the GTE predicate on the "content_md" field.
func ContentMdGTE(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldGTE(FieldContentMd, v))
}

// ContentMdLT applies the LT predicate on the "content_md" field.
func ContentMdLT(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldLT(FieldContentMd, v))
}

// ContentMdLTE applies the LTE predicate on the "content_md" field.
func ContentMdLTE(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldLTE(FieldContentMd, v))
}

// ContentMdContains applies the Contains predicate on the "content_md" field.
func ContentMdContains(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldContains(FieldContentMd, v))
}

// ContentMdHasPrefix applies the HasPrefix predicate on the "content_md" field.
func ContentMdHasPrefix(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldHasPrefix(FieldContentMd, v))
}

// ContentMdHasSuffix applies the HasSuffix predicate on the "content_md" field.
func ContentMdHasSuffix(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldHasSuffix(FieldContentMd, v))
}

// ContentMdEqualFold applies the EqualFold predicate on the "content_md" field.
func ContentMdEqualFold(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEqualFold(FieldContentMd, v))
}

// ContentMdContainsFold applies the ContainsFold predicate on the "content_md" field.
func ContentMdContainsFold(v string) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldContainsFold(FieldContentMd, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldLTE(FieldVersion, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNEQ(FieldActive, v))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNotNull(FieldPublishedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasParticipants applies the HasEdge predicate on the "participants" edge.
func HasParticipants() predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ParticipantsTable, ParticipantsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParticipantsWith applies the HasEdge predicate on the "participants" edge with a given conditions (other predicates).
func HasParticipantsWith(preds ...predicate.CarpoolParticipant) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(func(s *sql.Selector) {
		step := newParticipantsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CarpoolNoticeVersion) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CarpoolNoticeVersion) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CarpoolNoticeVersion) predicate.CarpoolNoticeVersion {
	return predicate.CarpoolNoticeVersion(sql.NotPredicates(p))
}
